package ir.sakhtemanyar.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity{
 static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api"; LinearLayout root; String session=""; JSONObject building; boolean resident=false;
 int teal=Color.rgb(13,148,136),ink=Color.rgb(15,23,42),bg=Color.rgb(246,248,250);
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(ink);showLogin();}
 TextView tv(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ink);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);t.setPadding(18,12,18,12);return t;}
 EditText inp(String h,boolean pass){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setGravity(Gravity.RIGHT);e.setSingleLine(true);e.setPadding(18,10,18,10);if(pass)e.setInputType(0x81);return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setAllCaps(false);GradientDrawable g=new GradientDrawable();g.setColor(teal);g.setCornerRadius(22);b.setBackground(g);return b;}
 void base(String title,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,25,22,25);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);ScrollView sc=new ScrollView(this);sc.addView(root);setContentView(sc);TextView h=tv(title,29,true);h.setTextColor(teal);root.addView(h);root.addView(tv(sub,14,false));}
 void showLogin(){base("ساختمان‌یار","مدیریت ساده، شفاف و امن ساختمان");EditText u=inp("نام کاربری",false),p=inp("رمز عبور",true);root.addView(u);root.addView(p);Button l=btn("ورود مدیر ساختمان");root.addView(l);Button lr=btn("ورود ساکن");root.addView(lr);Button r=btn("ثبت مدیر اولیه");root.addView(r);root.addView(tv("تأیید ایمیلی در نسخه فعلی خاموش است و مدیرکل می‌تواند بعداً آن را فعال کند.",12,false));l.setOnClickListener(v->{JSONObject q=new JSONObject();put(q,"action","login_manager");put(q,"username",u.getText().toString().trim());put(q,"password",p.getText().toString());request(q);});lr.setOnClickListener(v->{JSONObject q=new JSONObject();put(q,"action","login_resident");put(q,"username",u.getText().toString().trim());put(q,"password",p.getText().toString());request(q);});r.setOnClickListener(v->showRegister());}
 void showRegister(){base("ثبت مدیر اولیه","ساختمان خود را بسازید و دوره آزمایشی را شروع کنید");EditText n=inp("نام ساختمان",false),a=inp("آدرس",false),u=inp("نام کاربری",false),p=inp("رمز عبور حداقل ۶ کاراکتر",true),p2=inp("تکرار رمز عبور",true);root.addView(n);root.addView(a);root.addView(u);root.addView(p);root.addView(p2);Button c=btn("ثبت مدیر و شروع دوره آزمایشی");Button back=btn("بازگشت");root.addView(c);root.addView(back);c.setOnClickListener(v->{if(n.length()==0||u.length()==0||p.length()<6||!p.getText().toString().equals(p2.getText().toString())){toast("اطلاعات ثبت نام را بررسی کنید");return;}JSONObject q=new JSONObject();put(q,"action","register_manager");put(q,"building_name",n.getText().toString());put(q,"address",a.getText().toString());put(q,"username",u.getText().toString());put(q,"password",p.getText().toString());request(q);});back.setOnClickListener(v->showLogin());}
 void showDashboard(){String name="ساختمان من",st="trial",ex="";try{name=building.optString("name",name);st=building.optString("subscription_status",st);ex=building.optString("subscription_expires_at","");}catch(Exception ignored){}base("داشبورد مدیر","ساختمان: "+name);root.addView(card("وضعیت اشتراک",statusText(st,ex)));Button units=btn("🏢 واحدها و ساکنان");Button costs=btn("💳 شارژ و هزینه‌ها");Button repair=btn("🛠 ثبت تعمیرات");Button pay=btn("🧾 بررسی پرداخت‌ها");Button plans=btn("⭐ اشتراک سامانه");Button refresh=btn("↻ بروزرسانی");Button out=btn("خروج");for(Button x:new Button[]{units,costs,repair,pay,plans,refresh,out})root.addView(x);units.setOnClickListener(v->unitsPage());costs.setOnClickListener(v->chargesPage());repair.setOnClickListener(v->repairDialog());pay.setOnClickListener(v->paymentPage());plans.setOnClickListener(v->plansPage());refresh.setOnClickListener(v->loadDashboard());out.setOnClickListener(v->{session="";building=null;showLogin();});loadDashboard();}
 String statusText(String s,String e){if("active".equals(s))return "فعال • پایان: "+e;if("expired".equals(s))return "منقضی شده";return "دوره آزمایشی • پایان: "+e;}
 void showResident(){base("داشبورد ساکن","اطلاعات واحد شما");Button refresh=btn("↻ بروزرسانی حساب");Button pay=btn("💳 ثبت پرداخت");Button out=btn("خروج");root.addView(refresh);root.addView(pay);root.addView(out);refresh.setOnClickListener(v->loadResident());pay.setOnClickListener(v->residentPaymentDialog());out.setOnClickListener(v->{session="";showLogin();});loadResident();}
 TextView card(String a,String b){TextView t=tv(a+"\n"+b,17,true);t.setBackgroundColor(Color.WHITE);margin(t,0,5,0,5);return t;}
 void unitsPage(){base("واحدها و ساکنان","هر ساختمان فقط داده‌های خودش را می‌بیند");Button add=btn("＋ افزودن واحد");root.addView(add);add.setOnClickListener(v->addUnitDialog());loadDashboard();}
 void chargesPage(){base("شارژ و هزینه‌ها","مبلغ به ریال ذخیره می‌شود و در رابط کاربری قابل نمایش به تومان است");Button add=btn("＋ ثبت شارژ / هزینه");root.addView(add);add.setOnClickListener(v->addChargeDialog());loadDashboard();}
 void paymentPage(){base("پرداخت‌ها","پرداخت‌های ثبت‌شده در این ساختمان");loadDashboard();}
 void plansPage(){base("اشتراک سامانه","طرح‌ها از تنظیمات مدیرکل می‌آیند");JSONObject q=new JSONObject();put(q,"action","list_plans");request(q);}
 void addUnitDialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText no=inp("شماره واحد",false),cnt=inp("تعداد نفرات",false),rn=inp("نام ساکن",false);x.addView(no);x.addView(cnt);x.addView(rn);new AlertDialog.Builder(this).setTitle("افزودن واحد").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_unit");put(q,"unit_no",no.getText().toString());put(q,"residents_count",parse(cnt.getText().toString(),1));put(q,"resident_name",rn.getText().toString());request(q);}).show();}
 void addChargeDialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText title=inp("عنوان",false),amt=inp("مبلغ (ریال)",false),desc=inp("توضیحات",false);x.addView(title);x.addView(amt);x.addView(desc);new AlertDialog.Builder(this).setTitle("ثبت شارژ / هزینه").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_charge");put(q,"title",title.getText().toString());put(q,"amount_rial",parseLong(amt.getText().toString(),0));put(q,"charge_type","charge");put(q,"allocation_method","per_unit");put(q,"description",desc.getText().toString());request(q);}).show();}
 void repairDialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText title=inp("عنوان تعمیر",false),amt=inp("مبلغ (ریال)",false),desc=inp("توضیحات",false);x.addView(title);x.addView(amt);x.addView(desc);new AlertDialog.Builder(this).setTitle("ثبت تعمیرات").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_repair");put(q,"title",title.getText().toString());put(q,"amount_rial",parseLong(amt.getText().toString(),0));put(q,"description",desc.getText().toString());request(q);}).show();}
 void residentPaymentDialog(){EditText amt=inp("مبلغ پرداختی (ریال)",false);new AlertDialog.Builder(this).setTitle("ثبت پرداخت").setView(amt).setNegativeButton("انصراف",null).setPositiveButton("ارسال برای تأیید مدیر",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_payment");put(q,"unit_id",building==null?"":building.optString("unit_id"));put(q,"amount_rial",parseLong(amt.getText().toString(),0));request(q);}).show();}
 void createResidentDialog(String unitId){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText name=inp("نام و نام خانوادگی",false),u=inp("نام کاربری ساکن",false),p=inp("رمز عبور",true);x.addView(name);x.addView(u);x.addView(p);new AlertDialog.Builder(this).setTitle("ساخت حساب ساکن").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ساخت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","create_resident");put(q,"unit_id",unitId);put(q,"full_name",name.getText().toString());put(q,"username",u.getText().toString());put(q,"password",p.getText().toString());request(q);}).show();}
 void loadDashboard(){JSONObject q=new JSONObject();put(q,"action","dashboard");request(q);}
 void loadResident(){JSONObject q=new JSONObject();put(q,"action","dashboard");request(q);}
 void request(JSONObject q){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setConnectTimeout(15000);c.setReadTimeout(20000);if(!session.isEmpty())c.setRequestProperty("Authorization","Bearer "+session);c.setDoOutput(true);c.getOutputStream().write(q.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONObject o=new JSONObject(sb.toString());runOnUiThread(()->handle(q.optString("action"),o,code));}catch(Exception e){runOnUiThread(()->toast("ارتباط با سامانه ناموفق بود"));}}).start();}
 void handle(String action,JSONObject o,int code){if(code>=400){toast(o.optString("error","خطا"));return;}if(action.equals("login_manager")||action.equals("register_manager")){resident=false;session=o.optString("session","");building=o.optJSONObject("building");showDashboard();return;}if(action.equals("login_resident")){resident=true;session=o.optString("session","");building=new JSONObject();put(building,"unit_id",o.optString("unit_id"));put(building,"building_id",o.optString("building_id"));put(building,"full_name",o.optString("full_name"));showResident();return;}if(action.equals("dashboard")){if(resident){renderResident(o);return;}JSONArray us=o.optJSONArray("units"),cs=o.optJSONArray("charges"),ps=o.optJSONArray("payments"),rs=o.optJSONArray("repairs");if(us!=null)root.addView(card("تعداد واحدها",String.valueOf(us.length())));if(cs!=null)for(int i=0;i<Math.min(10,cs.length());i++){JSONObject z=cs.optJSONObject(i);root.addView(card(z.optString("title"),money(z.optString("amount_rial",z.optString("amount")))+" تومان"));}if(rs!=null)root.addView(card("تعداد تعمیرات",String.valueOf(rs.length())));if(ps!=null)root.addView(card("پرداخت‌های ثبت‌شده",String.valueOf(ps.length())));return;}if(action.equals("list_plans")){JSONArray a=o.optJSONArray("plans");if(a==null)a=o.optJSONArray("data");if(a!=null)for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);root.addView(card(p.optString("name"),money(p.optString("price_rial"))+" تومان • "+p.optString("duration_days")+" روز"));}return;}if(action.equals("add_unit")){toast("واحد ثبت شد");return;}if(action.equals("create_resident")){toast("حساب ساکن ساخته شد");return;}toast("عملیات با موفقیت انجام شد");}
 void renderResident(JSONObject o){root.addView(card("واحد",o.optJSONObject("unit")!=null?o.optJSONObject("unit").optString("unit_no"):"-"));JSONArray cs=o.optJSONArray("charges"),ps=o.optJSONArray("payments");if(cs!=null)for(int i=0;i<Math.min(20,cs.length());i++){JSONObject z=cs.optJSONObject(i);root.addView(card(z.optString("title"),money(z.optString("amount_rial",z.optString("amount")))+" تومان"));}if(ps!=null)root.addView(card("پرداخت‌های شما",String.valueOf(ps.length())));}
 String money(String s){try{return String.format(java.util.Locale.US,"%,d",Long.parseLong(s.replace(",",""))/10);}catch(Exception e){return s;}}
 static void put(JSONObject o,String k,Object v){try{o.put(k,v);}catch(Exception ignored){}}
 static int parse(String s,int d){try{return Integer.parseInt(s.replace(",",""));}catch(Exception e){return d;}}
 static long parseLong(String s,long d){try{return Long.parseLong(s.replace(",",""));}catch(Exception e){return d;}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 void margin(View v,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(l,t,r,b);v.setLayoutParams(p);}
}
