package ir.sakhtemanyar.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.content.Context;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity{
 static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api";
 LinearLayout root,content; FrameLayout frame; View drawer; String session=""; JSONObject building; boolean resident=false; String page="login";
 int teal=Color.rgb(13,148,136), tealDark=Color.rgb(15,118,110), ink=Color.rgb(15,23,42), muted=Color.rgb(100,116,139), bg=Color.rgb(245,247,250), white=Color.WHITE;
 int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(ink);showLogin();}
 @Override public void onBackPressed(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){closeDrawer();return;}if(page.equals("register")){showLogin();return;}if(page.equals("dashboard")||page.equals("resident")){showLogin();return;}if(!page.equals("login")){showDashboard();return;}super.onBackPressed();}
 TextView tv(String s,float z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(ink);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);t.setPadding(dp(16),dp(10),dp(16),dp(10));return t;}
 EditText inp(String h,boolean pass){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setTextColor(ink);e.setHintTextColor(muted);e.setGravity(Gravity.RIGHT);e.setSingleLine(true);e.setPadding(dp(16),dp(8),dp(16),dp(8));GradientDrawable g=new GradientDrawable();g.setColor(white);g.setStroke(dp(1),Color.rgb(220,226,234));g.setCornerRadius(dp(14));e.setBackground(g);if(pass)e.setInputType(0x81);return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(white);b.setAllCaps(false);b.setMinHeight(dp(50));b.setPadding(dp(12),0,dp(12),0);GradientDrawable g=new GradientDrawable();g.setColor(teal);g.setCornerRadius(dp(15));b.setBackground(g);return b;}
 Button ghost(String s){Button b=btn(s);b.setTextColor(ink);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(235,240,246));g.setCornerRadius(dp(15));b.setBackground(g);return b;}
 void base(String title,String sub,boolean nav){
  page=title.equals("ساختمان‌یار")?"login":title.equals("ثبت مدیر اولیه")?"register":title.equals("داشبورد مدیر")?"dashboard":title.equals("داشبورد ساکن")?"resident":"page";
  frame=new FrameLayout(this);frame.setBackgroundColor(bg);setContentView(frame);
  ScrollView sc=new ScrollView(this);sc.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sc.addView(root);frame.addView(sc,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(0,0,0,dp(8));
  if(nav){Button menu=iconButton("☰");head.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(52)));menu.setOnClickListener(v->openDrawer());}
  LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.setGravity(Gravity.RIGHT);TextView h=tv(title,25,true);h.setTextColor(tealDark);TextView ss=tv(sub,13,false);ss.setTextColor(muted);titles.addView(h);titles.addView(ss);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);head.addView(titles,tp);root.addView(head);
 }
 Button iconButton(String s){Button b=ghost(s);b.setTextSize(23);return b;}
 void showLogin(){base("ساختمان‌یار","مدیریت ساده، شفاف و امن ساختمان",false);root.addView(space(8));TextView welcome=tv("ورود به حساب",20,true);root.addView(welcome);root.addView(tv("مدیر یا ساکن ساختمان وارد حساب خود شوید.",13,false));EditText u=inp("نام کاربری",false),p=inp("رمز عبور",true);addGap(u);addGap(p);Button l=btn("ورود مدیر ساختمان");Button lr=ghost("ورود ساکن");Button r=ghost("＋ ثبت مدیر اولیه");root.addView(l);root.addView(space(8));root.addView(lr);root.addView(space(8));root.addView(r);root.addView(space(12));TextView info=tv("مدیر اولیه می‌تواند ساختمان و حساب مدیر را ایجاد کند و دوره آزمایشی را آغاز کند.",12,false);info.setTextColor(muted);root.addView(info);
  l.setOnClickListener(v->{JSONObject q=new JSONObject();put(q,"action","login_manager");put(q,"username",u.getText().toString().trim());put(q,"password",p.getText().toString());request(q);});
  lr.setOnClickListener(v->{JSONObject q=new JSONObject();put(q,"action","login_resident");put(q,"username",u.getText().toString().trim());put(q,"password",p.getText().toString());request(q);});r.setOnClickListener(v->showRegister());}
 void showRegister(){base("ثبت مدیر اولیه","ساختمان خود را بسازید و دوره آزمایشی را شروع کنید",true);EditText n=inp("نام ساختمان",false),a=inp("آدرس",false),u=inp("نام کاربری مدیر",false),p=inp("رمز عبور حداقل ۶ کاراکتر",true),p2=inp("تکرار رمز عبور",true);addGap(n);addGap(a);addGap(u);addGap(p);addGap(p2);Button c=btn("ثبت مدیر و شروع دوره آزمایشی");root.addView(c);root.addView(space(8));Button back=ghost("بازگشت");root.addView(back);c.setOnClickListener(v->{if(n.length()==0||u.length()==0||p.length()<6||!p.getText().toString().equals(p2.getText().toString())){toast("اطلاعات ثبت نام را بررسی کنید");return;}JSONObject q=new JSONObject();put(q,"action","register_manager");put(q,"building_name",n.getText().toString().trim());put(q,"address",a.getText().toString().trim());put(q,"username",u.getText().toString().trim());put(q,"password",p.getText().toString());request(q);});back.setOnClickListener(v->showLogin());}
 void showDashboard(){String name="ساختمان من",st="trial",ex="";try{if(building!=null){name=building.optString("name",name);st=building.optString("subscription_status",st);ex=building.optString("subscription_expires_at","");}}catch(Exception ignored){}base("داشبورد مدیر","ساختمان: "+name,true);root.addView(statusCard(statusText(st,ex)));root.addView(space(12));TextView hint=tv("از منوی ☰ بخش موردنظر را انتخاب کنید.",14,true);hint.setTextColor(muted);root.addView(hint);root.addView(space(8));summaryCard("🏢","واحدها و ساکنان","مدیریت واحدها و حساب ساکنان");summaryCard("💳","شارژ و هزینه‌ها","ثبت و مدیریت شارژ ساختمان");summaryCard("🛠","تعمیرات","ثبت هزینه و سوابق تعمیرات");summaryCard("🧾","پرداخت‌ها","بررسی پرداخت‌های ثبت‌شده");summaryCard("⭐","اشتراک سامانه","مشاهده طرح‌های اشتراک");loadDashboard();}
 void summaryCard(String icon,String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(12),dp(16),dp(12));GradientDrawable g=new GradientDrawable();g.setColor(white);g.setCornerRadius(dp(18));g.setStroke(dp(1),Color.rgb(229,234,241));c.setBackground(g);TextView a=tv(icon+"  "+title,17,true);a.setTextColor(ink);TextView b=tv(sub,12,false);b.setTextColor(muted);c.addView(a);c.addView(b);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));root.addView(c,lp);}
 TextView statusCard(String s){TextView t=tv("وضعیت اشتراک\n"+s,16,true);t.setTextColor(tealDark);GradientDrawable g=new GradientDrawable();g.setColor(Color.rgb(230,247,244));g.setCornerRadius(dp(18));t.setBackground(g);return t;}
 String statusText(String s,String e){if("active".equals(s))return "فعال • پایان: "+e;if("expired".equals(s))return "منقضی شده";return "دوره آزمایشی • پایان: "+e;}
 void showResident(){base("داشبورد ساکن","اطلاعات واحد شما",true);root.addView(statusCard("حساب ساکن فعال"));root.addView(space(10));Button refresh=btn("↻ بروزرسانی حساب");Button pay=ghost("💳 ثبت پرداخت");Button out=ghost("خروج از حساب");root.addView(refresh);root.addView(space(8));root.addView(pay);root.addView(space(8));root.addView(out);refresh.setOnClickListener(v->loadResident());pay.setOnClickListener(v->residentPaymentDialog());out.setOnClickListener(v->{session="";building=null;showLogin();});loadResident();}
 void openDrawer(){if(frame==null||drawer!=null&&drawer.getVisibility()==View.VISIBLE)return;final View overlay=new View(this);overlay.setBackgroundColor(0x55000000);FrameLayout.LayoutParams op=new FrameLayout.LayoutParams(-1,-1);frame.addView(overlay,op);overlay.setOnClickListener(v->closeDrawer());LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(18),dp(24),dp(18),dp(18));panel.setBackgroundColor(white);TextView brand=tv("ساختمان‌یار",23,true);brand.setTextColor(tealDark);panel.addView(brand);TextView who=tv(resident?"حساب ساکن":"حساب مدیر ساختمان",12,false);who.setTextColor(muted);panel.addView(who);panel.addView(space(16));if(resident){drawerItem(panel,"⌂  داشبورد",()->{closeDrawer();showResident();});drawerItem(panel,"💳 ثبت پرداخت",()->{closeDrawer();residentPaymentDialog();});}else{drawerItem(panel,"⌂  داشبورد",()->{closeDrawer();showDashboard();});drawerItem(panel,"🏢  واحدها و ساکنان",()->{closeDrawer();unitsPage();});drawerItem(panel,"💳  شارژ و هزینه‌ها",()->{closeDrawer();chargesPage();});drawerItem(panel,"🛠  تعمیرات",()->{closeDrawer();repairPage();});drawerItem(panel,"🧾  پرداخت‌ها",()->{closeDrawer();paymentPage();});drawerItem(panel,"⭐  اشتراک سامانه",()->{closeDrawer();plansPage();});}Space sp=new Space(this);panel.addView(sp,new LinearLayout.LayoutParams(1,0,1));drawerItem(panel,"↻  بروزرسانی",()->{closeDrawer();if(resident)loadResident();else loadDashboard();});drawerItem(panel,"خروج",()->{closeDrawer();session="";building=null;showLogin();});drawer=panel;FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(310),-1,Gravity.RIGHT);frame.addView(drawer,pp);}
 void drawerItem(LinearLayout p,String s,final Runnable r){Button b=ghost(s);b.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);b.setTextSize(15);p.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->r.run());}
 void closeDrawer(){if(frame!=null&&drawer!=null){frame.removeView(drawer);drawer=null;}}
 void unitsPage(){base("واحدها و ساکنان","مدیریت واحدها و حساب ساکنان",true);Button add=btn("＋ افزودن واحد");root.addView(add);root.addView(space(10));root.addView(tv("برای افزودن واحد، شماره واحد و اطلاعات اولیه ساکن را ثبت کنید.",13,false));add.setOnClickListener(v->addUnitDialog());}
 void chargesPage(){base("شارژ و هزینه‌ها","ثبت هزینه و شارژ ساختمان",true);Button add=btn("＋ ثبت شارژ / هزینه");root.addView(add);root.addView(space(10));root.addView(tv("هزینه‌ها جدا از داشبورد نمایش داده می‌شوند.",13,false));add.setOnClickListener(v->addChargeDialog());}
 void repairPage(){base("تعمیرات","ثبت و پیگیری هزینه‌های تعمیرات",true);Button add=btn("＋ ثبت تعمیرات");root.addView(add);root.addView(space(10));root.addView(tv("سوابق تعمیرات این ساختمان در سامانه ثبت می‌شود.",13,false));add.setOnClickListener(v->repairDialog());}
 void paymentPage(){base("پرداخت‌ها","بررسی پرداخت‌های ثبت‌شده در ساختمان",true);root.addView(tv("پرداخت‌های ثبت‌شده از سامانه دریافت می‌شوند.",14,false));loadDashboard();}
 void plansPage(){base("اشتراک سامانه","طرح‌ها از تنظیمات مدیرکل می‌آیند",true);JSONObject q=new JSONObject();put(q,"action","list_plans");request(q);}
 void addUnitDialog(){LinearLayout x=dialogBox();EditText no=inp("شماره واحد",false),cnt=inp("تعداد نفرات",false),rn=inp("نام ساکن",false);x.addView(no);x.addView(cnt);x.addView(rn);new AlertDialog.Builder(this).setTitle("افزودن واحد").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_unit");put(q,"unit_no",no.getText().toString());put(q,"residents_count",parse(cnt.getText().toString(),1));put(q,"resident_name",rn.getText().toString());request(q);}).show();}
 void addChargeDialog(){LinearLayout x=dialogBox();EditText title=inp("عنوان",false),amt=inp("مبلغ (ریال)",false),desc=inp("توضیحات",false);x.addView(title);x.addView(amt);x.addView(desc);new AlertDialog.Builder(this).setTitle("ثبت شارژ / هزینه").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_charge");put(q,"title",title.getText().toString());put(q,"amount_rial",parseLong(amt.getText().toString(),0));put(q,"charge_type","charge");put(q,"allocation_method","per_unit");put(q,"description",desc.getText().toString());request(q);}).show();}
 void repairDialog(){LinearLayout x=dialogBox();EditText title=inp("عنوان تعمیر",false),amt=inp("مبلغ (ریال)",false),desc=inp("توضیحات",false);x.addView(title);x.addView(amt);x.addView(desc);new AlertDialog.Builder(this).setTitle("ثبت تعمیرات").setView(x).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_repair");put(q,"title",title.getText().toString());put(q,"amount_rial",parseLong(amt.getText().toString(),0));put(q,"description",desc.getText().toString());request(q);}).show();}
 void residentPaymentDialog(){EditText amt=inp("مبلغ پرداختی (ریال)",false);new AlertDialog.Builder(this).setTitle("ثبت پرداخت").setView(amt).setNegativeButton("انصراف",null).setPositiveButton("ارسال برای تأیید مدیر",(d,w)->{JSONObject q=new JSONObject();put(q,"action","add_payment");put(q,"unit_id",building==null?"":building.optString("unit_id"));put(q,"amount_rial",parseLong(amt.getText().toString(),0));request(q);}).show();}
 LinearLayout dialogBox(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(8),dp(4),dp(8),dp(4));return x;}
 void loadDashboard(){JSONObject q=new JSONObject();put(q,"action","dashboard");request(q);}
 void loadResident(){JSONObject q=new JSONObject();put(q,"action","dashboard");request(q);}
 void request(JSONObject q){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setConnectTimeout(15000);c.setReadTimeout(20000);if(!session.isEmpty())c.setRequestProperty("Authorization","Bearer "+session);c.setDoOutput(true);c.getOutputStream().write(q.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONObject o=new JSONObject(sb.toString());runOnUiThread(()->handle(q.optString("action"),o,code));}catch(Exception e){runOnUiThread(()->toast("ارتباط با سامانه ناموفق بود"));}}).start();}
 void handle(String action,JSONObject o,int code){if(code>=400){toast(o.optString("error","خطا"));return;}if(action.equals("login_manager")||action.equals("register_manager")){resident=false;session=o.optString("session","");building=o.optJSONObject("building");showDashboard();return;}if(action.equals("login_resident")){resident=true;session=o.optString("session","");building=new JSONObject();put(building,"unit_id",o.optString("unit_id"));put(building,"building_id",o.optString("building_id"));put(building,"full_name",o.optString("full_name"));showResident();return;}if(action.equals("dashboard")){if(resident){renderResident(o);return;}if(page.equals("dashboard")){JSONArray us=o.optJSONArray("units"),ps=o.optJSONArray("payments");if(us!=null)root.addView(card("تعداد واحدها",String.valueOf(us.length())));if(ps!=null)root.addView(card("پرداخت‌های ثبت‌شده",String.valueOf(ps.length())));}return;}if(action.equals("list_plans")){JSONArray a=o.optJSONArray("plans");if(a==null)a=o.optJSONArray("data");if(a!=null)for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);root.addView(card(p.optString("name"),money(p.optString("price_rial"))+" تومان • "+p.optString("duration_days")+" روز"));}return;}if(action.equals("add_unit")){toast("واحد ثبت شد");return;}if(action.equals("create_resident")){toast("حساب ساکن ساخته شد");return;}if(action.equals("add_charge")){toast("شارژ / هزینه ثبت شد");return;}if(action.equals("add_repair")){toast("تعمیرات ثبت شد");return;}if(action.equals("add_payment")){toast("پرداخت برای تأیید مدیر ارسال شد");return;}toast("عملیات با موفقیت انجام شد");}
 void renderResident(JSONObject o){if(!page.equals("resident"))return;root.addView(card("واحد",o.optJSONObject("unit")!=null?o.optJSONObject("unit").optString("unit_no"):"-"));JSONArray cs=o.optJSONArray("charges"),ps=o.optJSONArray("payments");if(cs!=null)for(int i=0;i<Math.min(20,cs.length());i++){JSONObject z=cs.optJSONObject(i);root.addView(card(z.optString("title"),money(z.optString("amount_rial",z.optString("amount")))+" تومان"));}if(ps!=null)root.addView(card("پرداخت‌های شما",String.valueOf(ps.length())));}
 TextView card(String a,String b){TextView t=tv(a+"\n"+b,16,true);GradientDrawable g=new GradientDrawable();g.setColor(white);g.setCornerRadius(dp(16));g.setStroke(dp(1),Color.rgb(229,234,241));t.setBackground(g);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));t.setLayoutParams(lp);return t;}
 String money(String s){try{return String.format(java.util.Locale.US,"%,d",Long.parseLong(s.replace(",",""))/10);}catch(Exception e){return s;}}
 static void put(JSONObject o,String k,Object v){try{o.put(k,v);}catch(Exception ignored){}}
 static int parse(String s,int d){try{return Integer.parseInt(s.replace(",",""));}catch(Exception e){return d;}}
 static long parseLong(String s,long d){try{return Long.parseLong(s.replace(",",""));}catch(Exception e){return d;}}
 TextView space(int h){TextView v=new TextView(this);v.setHeight(dp(h));return v;}
 void addGap(View v){root.addView(v);root.addView(space(9));}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
