package com.sakhtemanyar;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class AdminActivity extends Activity {
    static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api";
    final ExecutorService io=Executors.newSingleThreadExecutor();
    LinearLayout root,body; String session=""; int navy=Color.rgb(18,28,52),teal=Color.rgb(0,155,150),purple=Color.rgb(116,82,190),gold=Color.rgb(232,160,54),red=Color.rgb(214,74,92),green=Color.rgb(40,164,111),bg=Color.rgb(245,247,251),white=Color.WHITE,dark=Color.rgb(30,39,57),muted=Color.rgb(105,116,135);
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    GradientDrawable grad(int a,int b,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(14),dp(7),dp(14),dp(7));return t;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setTextColor(dark);e.setHintTextColor(Color.rgb(150,158,173));e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setSingleLine(true);e.setPadding(dp(15),0,dp(15),0);e.setBackground(bg(white,15));return e;}
    Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(white);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(c,16));return b;}
    Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),dp(8),dp(10),dp(8));bar.setBackground(grad(navy,Color.rgb(35,51,86),0));TextView back=tv("‹",30,white);back.setGravity(Gravity.CENTER);bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView t=tv(title,19,white);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));TextView lock=tv("مدیرکل  •  🔐",12,Color.rgb(205,220,240));bar.addView(lock,new LinearLayout.LayoutParams(dp(110),dp(48)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));back.setOnClickListener(v->{if(session.isEmpty())finish();else dashboard();});ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(18),dp(16),dp(35));body.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));}
    void showLogin(){session="";base("ورود مستقل مدیرکل سامانه");body.setGravity(Gravity.CENTER_HORIZONTAL);body.addView(gap(28));LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setGravity(Gravity.CENTER);brand.setPadding(dp(18),dp(20),dp(18),dp(20));brand.setBackground(grad(navy,purple,26));TextView a=tv("ساختمان‌یار",30,white);a.setGravity(Gravity.CENTER);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);brand.addView(a);TextView b=tv("مرکز کنترل و مدیریت کل سامانه",14,Color.rgb(220,230,245));b.setGravity(Gravity.CENTER);brand.addView(b);body.addView(brand,new LinearLayout.LayoutParams(-1,dp(142)));body.addView(gap(24));TextView h=tv("ورود به حساب مدیرکل",18,dark);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));EditText u=input("نام کاربری مدیرکل"),p=input("رمز عبور مدیرکل");p.setInputType(129);body.addView(u,new LinearLayout.LayoutParams(-1,dp(58)));body.addView(gap(10));body.addView(p,new LinearLayout.LayoutParams(-1,dp(58)));body.addView(gap(14));Button login=btn("ورود امن به پنل مدیرکل",teal);body.addView(login,new LinearLayout.LayoutParams(-1,dp(56)));TextView note=tv("این بخش کاملاً جدا از پنل مدیر ساختمان و ساکن است.",12,muted);note.setGravity(Gravity.CENTER);body.addView(note,new LinearLayout.LayoutParams(-1,dp(48)));login.setOnClickListener(v->{String su=u.getText().toString().trim(),sp=p.getText().toString();if(su.isEmpty()||sp.isEmpty()){toast("نام کاربری و رمز عبور مدیرکل را وارد کنید");return;}login(su,sp);});}
    void login(String u,String p){io.submit(()->{try{JSONObject j=new JSONObject(post(new JSONObject().put("action","admin_login").put("username",u).put("password",p),null));if(j.has("error"))throw new Exception(j.getString("error"));session=j.getString("session");runOnUiThread(this::dashboard);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
    void dashboard(){base("داشبورد مدیرکل سامانه");hero("مرکز کنترل ساختمان‌یار","مدیریت ساختمان‌ها، اشتراک‌ها، مالی و تنظیمات سامانه");call("admin_dashboard",j->{org.json.JSONObject s=j.optJSONObject("summary");LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);stat(row,"ساختمان‌ها",s==null?"0":s.optString("total_buildings"),teal);stat(row,"فعال",s==null?"0":s.optString("active"),green);body.addView(row,new LinearLayout.LayoutParams(-1,dp(92)));LinearLayout row2=new LinearLayout(this);row2.setOrientation(LinearLayout.HORIZONTAL);row2.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);stat(row2,"آزمایشی",s==null?"0":s.optString("trial"),purple);stat(row2,"در انتظار",String.valueOf(pending(j.optJSONArray("requests"))),gold);body.addView(row2,new LinearLayout.LayoutParams(-1,dp(92)));title("مدیریت سریع");card("ساختمان‌ها","مشاهده، ویرایش و فعال/متوقف کردن ساختمان‌ها","▣",teal,v->buildings(j));card("اشتراک‌ها","ساخت و ویرایش طرح‌های اشتراک","★",purple,v->plans(j));card("درخواست‌ها","تأیید یا رد درخواست اشتراک","✓",gold,v->requests(j));card("مالی سامانه","گردش پرداخت‌ها و هزینه‌ها","₮",green,v->finance());card("تنظیمات","نام برنامه، دوره آزمایشی و درگاه","⚙",teal,v->settings(j));card("گزارش فعالیت","ثبت عملیات مدیرکل","◉",navy,v->audit());});}
    int pending(JSONArray a){int n=0;if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&"pending".equals(x.optString("status")))n++;}return n;}
    void hero(String a,String b){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(20),dp(17),dp(20),dp(17));h.setBackground(grad(navy,purple,25));TextView x=tv(a,22,white);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(x);h.addView(tv(b,13,Color.rgb(215,225,242)));body.addView(h,new LinearLayout.LayoutParams(-1,dp(112)));body.addView(gap(15));}
    void title(String s){TextView t=tv(s,18,dark);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(t,new LinearLayout.LayoutParams(-1,dp(44)));}
    void stat(LinearLayout row,String l,String v,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(12),dp(7),dp(12),dp(7));x.setBackground(bg(white,18));x.addView(tv(l,11,muted));TextView z=tv(v,20,c);z.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(z);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(78),1);lp.setMargins(dp(4),dp(4),dp(4),dp(4));row.addView(x,lp);}
    void card(String h,String sub,String icon,int c,View.OnClickListener l){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(10),dp(5),dp(8),dp(5));x.setBackground(bg(white,19));TextView i=tv(icon,25,c);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(dp(55),dp(64)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView a=tv(h,15,dark);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tx.addView(a);tx.addView(tv(sub,11,muted));x.addView(tx,new LinearLayout.LayoutParams(0,dp(64),1));x.addView(tv("‹",25,muted),new LinearLayout.LayoutParams(dp(34),dp(64)));x.setOnClickListener(l);body.addView(x,new LinearLayout.LayoutParams(-1,dp(74)));body.addView(gap(9));}
    void buildings(JSONObject all){base("مدیریت ساختمان‌ها");title("ساختمان‌های ثبت‌شده");JSONArray a=all.optJSONArray("buildings");if(a==null||a.length()==0){empty("هنوز ساختمانی ثبت نشده است");return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;final JSONObject q=x;String st=q.optString("subscription_status");int c="active".equals(st)?green:"suspended".equals(st)?red:"trial".equals(st)?purple:gold;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(12),dp(16),dp(12));box.setBackground(bg(white,20));TextView n=tv(q.optString("name","بدون نام"),17,dark);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);box.addView(n);box.addView(tv(q.optString("address","بدون آدرس"),12,muted));box.addView(tv("وضعیت: "+safe(q.optString("subscription_status")),13,c));Button edit=btn("ویرایش / تغییر وضعیت",c);box.addView(edit,new LinearLayout.LayoutParams(-1,dp(48)));edit.setOnClickListener(v->editBuilding(q));body.addView(box,new LinearLayout.LayoutParams(-1,dp(142)));body.addView(gap(10));}}
    void editBuilding(JSONObject q){final EditText n=input("نام ساختمان"),a=input("آدرس ساختمان");n.setText(safe(q.optString("name")));a.setText(safe(q.optString("address")));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(12),dp(5),dp(12),0);l.addView(n,new LinearLayout.LayoutParams(-1,dp(55)));l.addView(gap(8));l.addView(a,new LinearLayout.LayoutParams(-1,dp(55)));new AlertDialog.Builder(this).setTitle("ویرایش ساختمان").setView(l).setNegativeButton("لغو",null).setPositiveButton("ذخیره",(d,w)->updateBuilding(q.optString("id"),n.getText().toString(),a.getText().toString(),q.optString("subscription_status"))).show();new AlertDialog.Builder(this).setTitle("وضعیت دسترسی").setItems(new String[]{"فعال","متوقف","آزمایشی","منقضی"},(d,which)->{String[] s={"active","suspended","trial","expired"};callObj(new JSONObject().put("action","admin_building_update").put("building_id",q.optString("id")).put("status",s[which]),z->dashboard());}).show();}
    void updateBuilding(String id,String n,String a,String status){callObj(new JSONObject().put("action","admin_building_update").put("building_id",id).put("name",n).put("address",a).put("status",status),z->dashboard());}
    void plans(JSONObject all){base("مدیریت طرح‌های اشتراک");Button add=btn("＋ ساخت طرح جدید",purple);body.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));body.addView(gap(12));add.setOnClickListener(v->planDialog(null));JSONArray a=all.optJSONArray("plans");if(a==null||a.length()==0){empty("طرحی وجود ندارد");return;}for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q==null)continue;final JSONObject p=q;LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(16),dp(12),dp(16),dp(12));x.setBackground(bg(white,20));TextView n=tv(safe(p.optString("name")),18,dark);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(n);x.addView(tv(money(p.optDouble("price_rial"))+"  •  "+p.optInt("duration_days")+" روز  •  "+(p.optBoolean("active")?"فعال":"غیرفعال"),13,teal));Button e=btn("ویرایش",purple);x.addView(e,new LinearLayout.LayoutParams(-1,dp(48)));e.setOnClickListener(v->planDialog(p));body.addView(x,new LinearLayout.LayoutParams(-1,dp(135)));body.addView(gap(9));}}
    void planDialog(JSONObject p){final EditText n=input("نام طرح"),d=input("مدت به روز"),pr=input("قیمت به ریال"),u=input("حداکثر واحد");if(p!=null){n.setText(safe(p.optString("name")));d.setText(safe(p.optString("duration_days")));pr.setText(safe(p.optString("price_rial")));u.setText(safe(p.optString("max_units")));}LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(12),0,dp(12),0);l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));l.addView(d,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));l.addView(pr,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));l.addView(u,new LinearLayout.LayoutParams(-1,dp(54)));AlertDialog dlg=new AlertDialog.Builder(this).setTitle(p==null?"ساخت طرح جدید":"ویرایش طرح").setView(l).setNegativeButton("لغو",null).setPositiveButton("ذخیره",null).create();dlg.setOnShowListener(v->dlg.getButton(-1).setOnClickListener(w->{try{JSONObject q=new JSONObject().put("name",n.getText().toString()).put("duration_days",Integer.parseInt(d.getText().toString())).put("price_rial",Long.parseLong(pr.getText().toString())).put("max_units",Integer.parseInt(u.getText().toString()));if(p==null){q.put("action","admin_create_plan");}else{q.put("action","admin_update_plan").put("plan_id",p.optString("id"));}callObj(q,z->{dlg.dismiss();dashboard();});}catch(Exception e){toast("مقادیر طرح نامعتبر است");}}));dlg.show();}
    void requests(JSONObject all){base("درخواست‌های اشتراک");title("درخواست‌های اخیر");JSONArray a=all.optJSONArray("requests");if(a==null||a.length()==0){empty("درخواستی وجود ندارد");return;}for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q==null)continue;final String id=q.optString("id"),status=q.optString("status");LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(15),dp(12),dp(15),dp(12));x.setBackground(bg(white,20));x.addView(tv("درخواست اشتراک",16,dark));x.addView(tv("ساختمان: "+safe(q.optString("building_id")),12,muted));x.addView(tv("طرح: "+safe(q.optString("subscription_plans")),12,teal));x.addView(tv("وضعیت: "+safe(status),13,"pending".equals(status)?gold:green));if("pending".equals(status)){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);Button ap=btn("تأیید",green),re=btn("رد",red);r.addView(ap,new LinearLayout.LayoutParams(0,dp(48),1));r.addView(re,new LinearLayout.LayoutParams(0,dp(48),1));x.addView(r);ap.setOnClickListener(v->subscription(id,"approved"));re.setOnClickListener(v->subscription(id,"rejected"));}body.addView(x,new LinearLayout.LayoutParams(-1,dp(165)));body.addView(gap(9));}}
    void subscription(String id,String status){callObj(new JSONObject().put("action","admin_subscription_action").put("request_id",id).put("status",status),z->dashboard());}
    TextView fieldLabel(String title,String desc){TextView l=tv(title,14,dark);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(l,new LinearLayout.LayoutParams(-1,dp(30)));if(desc!=null&&!desc.isEmpty())body.addView(tv(desc,11,muted),new LinearLayout.LayoutParams(-1,dp(28)));return l;}
    void settings(JSONObject all){base("تنظیمات سامانه");title("تنظیمات مرکزی");body.addView(tv("هر گزینه فقط یک مسئولیت دارد؛ مقدار null یا خالی در این صفحه نمایش داده نمی‌شود.",12,muted),new LinearLayout.LayoutParams(-1,dp(42)));org.json.JSONObject s=all.optJSONObject("settings");final EditText name=input("نام برنامه");final EditText trial=input("تعداد روز دوره آزمایشی");final EditText phone=input("شماره پشتیبانی");final EditText email=input("ایمیل پشتیبانی");final EditText logo=input("آدرس لوگوی برنامه");String app=safe(s==null?"":s.optString("app_name"));String days=safe(s==null?"":s.optString("free_trial_days"));String ph=safe(s==null?"":s.optString("support_phone"));String em=safe(s==null?"":s.optString("support_email"));String lg=safe(s==null?"":s.optString("logo_url"));name.setText(app);trial.setText(days);phone.setText(ph);email.setText(em);logo.setText(lg);fieldLabel("اسم برنامه","نامی که در برنامه به کاربران نمایش داده می‌شود");body.addView(name,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(10));fieldLabel("دوره آزمایشی","تعداد روز استفاده رایگان ساختمان‌ها");body.addView(trial,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(10));fieldLabel("شماره پشتیبانی","شماره‌ای که برای تماس با پشتیبانی نمایش داده می‌شود");body.addView(phone,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(10));fieldLabel("ایمیل پشتیبانی","ایمیل تماس با پشتیبانی سامانه");body.addView(email,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(10));fieldLabel("لوگوی برنامه","فعلاً آدرس تصویر لوگو؛ در نسخه بعدی انتخاب مستقیم عکس هم اضافه می‌شود");body.addView(logo,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(14));Button save=btn("ذخیره تنظیمات",teal);body.addView(save,new LinearLayout.LayoutParams(-1,dp(54)));save.setOnClickListener(v->{try{String dayText=trial.getText().toString().trim();if(dayText.isEmpty())dayText="30";callObj(new JSONObject().put("action","admin_update_settings").put("app_name",safe(name.getText().toString().trim())).put("free_trial_days",Integer.parseInt(dayText)).put("support_phone",safe(phone.getText().toString().trim())).put("support_email",safe(email.getText().toString().trim())).put("logo_url",safe(logo.getText().toString().trim())),z->toast("تنظیمات با موفقیت ذخیره شد"));}catch(Exception e){toast("تعداد روز دوره آزمایشی باید عدد باشد");}});}
    void finance(){base("مالی سامانه");title("گردش مالی");call("admin_dashboard",j->{org.json.JSONObject s=j.optJSONObject("summary");info("پرداخت‌های تأییدشده",money(s==null?0:s.optDouble("approved_payments")),green);info("هزینه‌های ثبت‌شده",money(s==null?0:s.optDouble("charges")),gold);info("تعمیرات ثبت‌شده",money(s==null?0:s.optDouble("repairs")),purple);});}
    void audit(){base("گزارش فعالیت مدیرکل");title("آخرین عملیات");call("admin_audit",j->{JSONArray a=j.optJSONArray("data");if(a==null||a.length()==0){empty("هنوز عملیاتی ثبت نشده است");return;}for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q!=null)item(safe(q.optString("action")),safe(q.optString("entity_type"))+"  •  "+safe(q.optString("created_at")));}});}
    void item(String h,String v){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(15),dp(10),dp(15),dp(10));x.setBackground(bg(white,18));TextView a=tv(h,14,dark);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(a);x.addView(tv(v,12,muted));body.addView(x,new LinearLayout.LayoutParams(-1,dp(72)));body.addView(gap(8));}
    void info(String h,String v,int c){LinearLayout x=new LinearLayout(this);x.setPadding(dp(15),dp(8),dp(15),dp(8));x.setOrientation(LinearLayout.VERTICAL);x.setBackground(bg(white,18));x.addView(tv(h,12,muted));TextView z=tv(v,19,c);z.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(z);body.addView(x,new LinearLayout.LayoutParams(-1,dp(78)));body.addView(gap(8));}
    void empty(String s){TextView t=tv(s,14,muted);t.setGravity(Gravity.CENTER);body.addView(t,new LinearLayout.LayoutParams(-1,dp(100)));}
    String safe(String s){if(s==null||s.trim().isEmpty()||"null".equalsIgnoreCase(s.trim()))return "";return s;}
    String money(double rial){return String.format(Locale.US,"%.0f تومان",rial/10.0);}
    void call(String action,Handler h){io.submit(()->{try{JSONObject j=new JSONObject(post(new JSONObject().put("action",action),session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()==null?"خطا در ارتباط با سامانه":e.getMessage()));}});}
    void callObj(JSONObject b,Handler h){io.submit(()->{try{JSONObject j=new JSONObject(post(b,session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()==null?"خطا در ارتباط با سامانه":e.getMessage()));}});}
    String post(JSONObject b,String tok)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(7000);c.setReadTimeout(9000);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(tok!=null&&!tok.isEmpty())c.setRequestProperty("Authorization","Bearer "+tok);c.getOutputStream().write(b.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();java.io.InputStream is=code<400?c.getInputStream():c.getErrorStream();java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=is.read(buf))!=-1)out.write(buf,0,n);String s=new String(out.toByteArray(),StandardCharsets.UTF_8);if(code>=400){try{JSONObject e=new JSONObject(s);if(e.has("error"))throw new Exception(e.getString("error"));}catch(org.json.JSONException ignored){}throw new Exception("خطای ارتباط با سرور ("+code+")");}return s;}
    void toast(String s){Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_LONG).show();}
    interface Handler{void handle(JSONObject j)throws Exception;}
}