package com.sakhtemanyar;
import ir.sakhtemanyar.app.BuildConfig;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import androidx.security.crypto.EncryptedSharedPreferences;import androidx.security.crypto.MasterKeys;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public class AdminActivity extends Activity{
 static final String API=BuildConfig.API_BASE_URL; LinearLayout root,content; SharedPreferences prefs; ExecutorService io=Executors.newFixedThreadPool(3);String session="",role="admin";ArrayDeque<String> stack=new ArrayDeque<>();ProgressBar busy;
 int navy=Color.rgb(8,25,42),teal=Color.rgb(0,153,145),blue=Color.rgb(66,112,195),red=Color.rgb(207,70,79),bg=Color.rgb(246,249,251),white=Color.WHITE,text=Color.rgb(25,38,52),muted=Color.rgb(105,120,133);int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(j(s));t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(12),dp(5),dp(12),dp(5));return t;}String j(String s){if(s==null)return"";java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\b(\\d{4}-\\d{2}-\\d{2})").matcher(s);StringBuffer b=new StringBuffer();while(m.find())m.appendReplacement(b,java.util.regex.Matcher.quoteReplacement(JalaliDate.format(m.group(1))));m.appendTail(b);return b.toString();}EditText in(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setTextColor(text);e.setGravity(Gravity.RIGHT);e.setSingleLine(true);e.setBackground(box(white,14));e.setPadding(dp(12),0,dp(12),0);return e;}Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setContentDescription(s);b.setAllCaps(false);b.setTextColor(white);b.setTextSize(14);b.setBackground(box(c,15));return b;}Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
 @Override public void onCreate(Bundle b){super.onCreate(b);try{String k=MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC);prefs=EncryptedSharedPreferences.create("sakhtemanyar_secure",k,this,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);}catch(Exception e){prefs=getSharedPreferences("sakhtemanyar_secure_fallback",MODE_PRIVATE);}String s=prefs.getString("session","");if(!s.isEmpty()&&"admin".equals(prefs.getString("role",""))){session=s;stack.add("home");home();}else login();}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
 @Override public void onBackPressed(){if(stack.size()>1){stack.removeLast();show(stack.peekLast());}else logout();}
 void frame(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(navy);TextView back=tv(stack.size()>1?"‹":"↪",30,white);back.setGravity(Gravity.CENTER);back.setContentDescription(stack.size()>1?"بازگشت":"خروج");bar.addView(back,new LinearLayout.LayoutParams(dp(55),dp(58)));TextView h=tv(title,18,white);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(h,new LinearLayout.LayoutParams(0,dp(58),1));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(62)));busy=new ProgressBar(this);busy.setVisibility(View.GONE);root.addView(busy,new LinearLayout.LayoutParams(-1,dp(4)));ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(15),dp(15),dp(15),dp(30));content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));back.setOnClickListener(v->{if(stack.size()>1){stack.removeLast();show(stack.peekLast());}else logout();});}
 void login(){frame("ورود مدیرکل سامانه");content.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(gap(20));EditText u=in("نام کاربری"),p=in("رمز عبور");p.setInputType(129);content.addView(u,new LinearLayout.LayoutParams(-1,dp(55)));content.addView(gap(10));content.addView(p,new LinearLayout.LayoutParams(-1,dp(55)));content.addView(gap(14));Button b=btn("ورود امن",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->io.submit(()->{try{JSONObject q=new JSONObject().put("action","admin_login").put("username",u.getText().toString().trim()).put("password",p.getText().toString());JSONObject r=new JSONObject(post(q,null));session=r.optString("access_token",r.optString("session",""));prefs.edit().putString("session",session).putString("refresh_token",r.optString("refresh_token","")).putString("role","admin").apply();stack.clear();stack.add("home");runOnUiThread(this::home);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));}
 void show(String p){if("home".equals(p))home();else if("buildings".equals(p))buildings();else if("plans".equals(p))plans();else if("settings".equals(p))settings();else if("finance".equals(p))finance();else if("audit".equals(p))audit();}
 void nav(String title,String page,int c){Button b=btn(title,c);content.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));content.addView(gap(8));b.setOnClickListener(v->{if(!stack.peekLast().equals(page))stack.add(page);show(page);});}
 void home(){frame("داشبورد مدیرکل");section("مدیریت کل سامانه","کنترل ساختمان‌ها، اشتراک‌ها، مالی و امنیت");nav("ساختمان‌ها","buildings",teal);nav("اشتراک‌ها","plans",blue);nav("مالی سامانه","finance",Color.rgb(40,157,105));nav("گزارش عملیات","audit",Color.rgb(92,70,164));nav("تنظیمات","settings",navy);nav("خروج از حساب","logout",red);}
 void section(String a,String b){TextView x=tv(a,21,navy);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(x,new LinearLayout.LayoutParams(-1,dp(42)));content.addView(tv(b,12,muted),new LinearLayout.LayoutParams(-1,dp(30)));}
 void buildings(){frame("ساختمان‌ها");io.submit(()->{try{JSONObject q=new JSONObject().put("action","admin_dashboard"),r=new JSONObject(post(q,session));JSONArray a=r.optJSONArray("buildings");runOnUiThread(()->{if(a==null||a.length()==0){content.addView(tv("ساختمانی ثبت نشده است",15,muted));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(box(white,16));card.addView(tv(x.optString("name"),16,navy));card.addView(tv("وضعیت ساختمان: "+x.optString("building_status")+" | اشتراک: "+x.optString("subscription_status"),12,muted));card.addView(tv("انقضا: "+x.optString("subscription_expires_at"),12,muted));Button edit=btn("ویرایش وضعیت",teal);card.addView(edit,new LinearLayout.LayoutParams(-1,dp(48)));edit.setOnClickListener(v->editBuilding(x));content.addView(card,new LinearLayout.LayoutParams(-1,dp(145)));content.addView(gap(8));}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
 void editBuilding(JSONObject x){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=in("نام ساختمان");n.setText(x.optString("name"));EditText ad=in("آدرس");ad.setText(x.optString("address"));Spinner bs=new Spinner(this);String[] bsv={"active","stopped","archived"};bs.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,bsv));Spinner ss=new Spinner(this);String[] ssv={"trial","active","expired","suspended"};ss.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ssv));l.addView(n);l.addView(gap(8));l.addView(ad);l.addView(gap(8));l.addView(bs);l.addView(gap(8));l.addView(ss);new AlertDialog.Builder(this).setTitle("ویرایش ساختمان").setView(scrollWrap(l)).setPositiveButton("ذخیره",(d,w)->io.submit(()->{try{JSONObject q=new JSONObject().put("action","admin_building_update").put("building_id",x.optString("id")).put("name",n.getText().toString().trim()).put("address",ad.getText().toString().trim()).put("building_status",bsv[bs.getSelectedItemPosition()]).put("subscription_status",ssv[ss.getSelectedItemPosition()]);post(q,session);runOnUiThread(this::buildings);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}})).setNegativeButton("لغو",null).show();}
 void plans(){frame("اشتراک‌ها");io.submit(()->{try{JSONObject r=new JSONObject(post(new JSONObject().put("action","admin_dashboard"),session));JSONArray a=r.optJSONArray("plans");runOnUiThread(()->{Button add=btn("＋ طرح جدید",teal);content.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));add.setOnClickListener(v->planDialog(null));for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(10),dp(14),dp(10));c.setBackground(box(white,16));c.addView(tv(x.optString("name"),16,navy));c.addView(tv("مدت: "+x.optInt("duration_days")+" روز | مبلغ: "+x.optLong("price_rial")+" ریال | فعال: "+x.optBoolean("active"),12,muted));Button e=btn("ویرایش",blue);c.addView(e,new LinearLayout.LayoutParams(-1,dp(45)));e.setOnClickListener(v->planDialog(x));content.addView(c,new LinearLayout.LayoutParams(-1,dp(120)));content.addView(gap(7));}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
 void planDialog(JSONObject x){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=in("نام طرح"),d=in("مدت به روز"),p=in("مبلغ به ریال"),m=in("حداکثر واحد");Switch active=new Switch(this);active.setText("فعال");if(x!=null)active.setChecked(x.optBoolean("active",true));if(x!=null){n.setText(x.optString("name"));d.setText(String.valueOf(x.optInt("duration_days")));p.setText(String.valueOf(x.optLong("price_rial")));m.setText(String.valueOf(x.optInt("max_units")));}for(EditText e:new EditText[]{n,d,p,m}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(gap(7));}l.addView(active,new LinearLayout.LayoutParams(-1,dp(48)));new AlertDialog.Builder(this).setTitle(x==null?"طرح جدید":"ویرایش طرح").setView(scrollWrap(l)).setPositiveButton("ذخیره",(q,w)->io.submit(()->{try{JSONObject b=new JSONObject().put("action",x==null?"admin_create_plan":"admin_update_plan").put("name",n.getText().toString().trim()).put("duration_days",Integer.parseInt(d.getText().toString())).put("price_rial",Long.parseLong(p.getText().toString())).put("max_units",Integer.parseInt(m.getText().toString()));if(x!=null)b.put("plan_id",x.optString("id"));b.put("active",active.isChecked());post(b,session);runOnUiThread(this::plans);}catch(Exception e){runOnUiThread(()->toast("اطلاعات طرح معتبر نیست"));}})).setNegativeButton("لغو",null).show();}
 void settings(){frame("تنظیمات");io.submit(()->{try{JSONObject r=new JSONObject(post(new JSONObject().put("action","admin_dashboard"),session)),x=r.optJSONObject("settings");runOnUiThread(()->{EditText name=in("نام سامانه"),trial=in("روزهای آزمایشی"),phone=in("تلفن پشتیبانی"),email=in("ایمیل پشتیبانی");name.setText(x.optString("app_name"));trial.setText(String.valueOf(x.optInt("free_trial_days")));phone.setText(x.optString("support_phone"));email.setText(x.optString("support_email"));for(EditText e:new EditText[]{name,trial,phone,email}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(8));}Button save=btn("ذخیره تنظیمات",teal);content.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));save.setOnClickListener(v->io.submit(()->{try{post(new JSONObject().put("action","admin_update_settings").put("app_name",name.getText().toString().trim()).put("free_trial_days",Integer.parseInt(trial.getText().toString())).put("support_phone",phone.getText().toString().trim()).put("support_email",email.getText().toString().trim()),session);runOnUiThread(()->toast("تنظیمات ذخیره شد"));}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
 void finance(){frame("مالی سامانه");io.submit(()->{try{JSONObject r=new JSONObject(post(new JSONObject().put("action","admin_finance"),session));JSONArray a=r.optJSONArray("transactions");runOnUiThread(()->{if(a==null||a.length()==0){content.addView(tv("تراکنشی ثبت نشده است",15,muted));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);content.addView(tv(x.optString("created_at")+" | "+x.optLong("amount_rial")+" ریال | "+x.optString("status"),13,navy),new LinearLayout.LayoutParams(-1,dp(62)));}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
 void audit(){frame("گزارش عملیات و امنیت");io.submit(()->{try{JSONObject r=new JSONObject(post(new JSONObject().put("action","admin_audit"),session));JSONArray a=r.optJSONArray("data");runOnUiThread(()->{for(int i=0;i<(a==null?0:a.length());i++){JSONObject x=a.optJSONObject(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(8),dp(12),dp(8));c.setBackground(box(white,14));c.addView(tv(x.optString("action")+" | "+x.optString("actor_type"),14,navy));c.addView(tv(x.optString("created_at"),11,muted));c.addView(tv(x.optString("details"),11,muted));content.addView(c,new LinearLayout.LayoutParams(-1,dp(105)));content.addView(gap(7));}});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
 void logout(){String old=session;session="";prefs.edit().clear().apply();if(!old.isEmpty())io.submit(()->{try{post(new JSONObject().put("action","logout"),old);}catch(Exception ignored){}});finish();}
 String post(JSONObject b,String auth)throws Exception{URL u=new URL(API);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setConnectTimeout(7000);c.setReadTimeout(9000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(auth!=null&&!auth.isEmpty())c.setRequestProperty("Authorization","Bearer "+auth);c.getOutputStream().write(b.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();String out=new String(in.readAllBytes(),StandardCharsets.UTF_8);c.disconnect();if(code>=400)throw new RuntimeException(new JSONObject(out).optString("error","خطای سرور"));return out;}
 void toast(String s){runOnUiThread(()->Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_LONG).show());}
    View scrollWrap(LinearLayout content){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(content);return sv;}

}