package com.sakhtemanyar;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api";
    LinearLayout root,content,drawer; String session="",role=""; final ArrayDeque<String> history=new ArrayDeque<>();
    final ExecutorService io=Executors.newSingleThreadExecutor(); int token=0;
    int navy=Color.rgb(7,22,38), teal=Color.rgb(0,150,145), teal2=Color.rgb(35,191,176), bg=Color.rgb(245,248,250), white=Color.WHITE, text=Color.rgb(24,35,48), muted=Color.rgb(104,119,132), gold=Color.rgb(221,153,45), red=Color.rgb(210,72,78), green=Color.rgb(38,157,104), blue=Color.rgb(72,111,196);
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    GradientDrawable gradient(int a,int b,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(14),dp(6),dp(14),dp(6));return t;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setTextColor(text);e.setHintTextColor(Color.rgb(150,160,170));e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setBackground(box(white,16));return e;}
    Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(white);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(box(c,17));b.setPadding(dp(8),0,dp(8),0);return b;}
    Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}

    void frame(String title,boolean inner){token++;root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),dp(8),dp(10),dp(8));bar.setBackground(gradient(navy,Color.rgb(11,48,67),0));
        TextView nav=tv(inner?"‹":"☰",30,white);nav.setGravity(Gravity.CENTER);bar.addView(nav,new LinearLayout.LayoutParams(dp(50),dp(48)));TextView t=tv(title,18,white);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));
        TextView brand=tv("ساختمان‌یار",12,Color.rgb(190,220,218));brand.setGravity(Gravity.CENTER);bar.addView(brand,new LinearLayout.LayoutParams(dp(90),dp(48)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(17),dp(17),dp(17),dp(32));content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        drawer=new LinearLayout(this);drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(dp(15),dp(18),dp(15),dp(22));drawer.setBackgroundColor(white);drawer.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(drawer,new LinearLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.84),-1));drawer.setVisibility(View.GONE);nav.setOnClickListener(v->{if(inner)backPage();else toggleDrawer();});
    }
    void toggleDrawer(){if(drawer!=null)drawer.setVisibility(drawer.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);}
    void open(String id){if(history.isEmpty()||!history.peekLast().equals(id))history.addLast(id);show(id);}
    void show(String id){if(id.equals("manager"))managerHome();else if(id.equals("units"))units();else if(id.equals("charges"))charges();else if(id.equals("repairs"))repairs();else if(id.equals("payments"))payments();else if(id.equals("plans"))plans();else if(id.equals("resident"))residentHome();else if(id.equals("resident_pay"))residentPay();else if(id.equals("admin"))adminHome();else if(id.equals("admin_buildings"))adminBuildings();else if(id.equals("admin_plans"))adminPlans();else if(id.equals("admin_settings"))adminSettings();else showLogin();}
    void backPage(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){history.removeLast();show(history.peekLast());}else{session="";role="";history.clear();showLogin();}}
    @Override public void onBackPressed(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){backPage();return;}if(!role.isEmpty()){session="";role="";history.clear();showLogin();return;}super.onBackPressed();}

    void showLogin(){role="";session="";history.clear();frame("ورود",false);content.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(gap(12));
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(22),dp(24),dp(22),dp(24));hero.setGravity(Gravity.CENTER);hero.setBackground(gradient(navy,Color.rgb(8,67,74),28));
        TextView logo=tv("ساختمان‌یار",32,white);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT,Typeface.BOLD);hero.addView(logo);TextView sub=tv("مدیریت ساختمان، ساده و شفاف",14,Color.rgb(205,231,229));sub.setGravity(Gravity.CENTER);hero.addView(sub);content.addView(hero,new LinearLayout.LayoutParams(-1,dp(155)));content.addView(gap(20));
        TextView h=tv("خوش آمدید",24,navy);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h,new LinearLayout.LayoutParams(-1,dp(45)));TextView hint=tv("نوع ورود خود را انتخاب کنید و وارد شوید",13,muted);content.addView(hint,new LinearLayout.LayoutParams(-1,dp(34)));
        EditText u=input("نام کاربری"),p=input("رمز عبور");p.setInputType(129);content.addView(u,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));content.addView(p,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(14));
        Button m=btn("ورود مدیر ساختمان  〉",teal),r=btn("ورود ساکن  〉",blue);content.addView(m,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));content.addView(r,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));
        Button a=btn("ورود مدیرکل سامانه  🔐",navy);content.addView(a,new LinearLayout.LayoutParams(-1,dp(52)));content.addView(gap(14));
        TextView or=tv("حساب مدیر ندارید؟",12,muted);or.setGravity(Gravity.CENTER);content.addView(or,new LinearLayout.LayoutParams(-1,dp(30)));Button reg=btn("＋ ثبت ساختمان و مدیر جدید",Color.rgb(91,111,123));content.addView(reg,new LinearLayout.LayoutParams(-1,dp(52)));
        m.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"manager"));r.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"resident"));a.setOnClickListener(v->startActivity(new Intent(this,AdminActivity.class)));reg.setOnClickListener(v->register());
    }
    void section(String s,String sub){TextView t=tv(s,19,navy);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(t,new LinearLayout.LayoutParams(-1,dp(38)));if(sub!=null)content.addView(tv(sub,12,muted),new LinearLayout.LayoutParams(-1,dp(30)));}
    void hero(String title,String sub,int accent){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(19),dp(17),dp(19),dp(17));h.setBackground(gradient(navy,accent,24));TextView a=tv(title,21,white);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(a);h.addView(tv(sub,12,Color.rgb(210,228,230)));content.addView(h,new LinearLayout.LayoutParams(-1,dp(108)));content.addView(gap(14));}
    void stat(String label,String value,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(11),dp(14),dp(10));x.setBackground(box(white,19));x.addView(tv(label,11,muted));TextView v=tv(value,21,c);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(v);content.addView(x,new LinearLayout.LayoutParams(-1,dp(76)));content.addView(gap(8));}
    void action(String label,String sub,String icon,String page,int c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(8),dp(6),dp(8),dp(6));x.setBackground(box(white,19));TextView i=tv(icon,25,c);i.setGravity(Gravity.CENTER);i.setBackground(box(Color.rgb(241,247,247),15));x.addView(i,new LinearLayout.LayoutParams(dp(56),dp(60)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView a=tv(label,15,navy);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tx.addView(a);tx.addView(tv(sub,11,muted));x.addView(tx,new LinearLayout.LayoutParams(0,dp(60),1));x.addView(tv("‹",26,muted),new LinearLayout.LayoutParams(dp(34),dp(60)));x.setOnClickListener(v->open(page));content.addView(x,new LinearLayout.LayoutParams(-1,dp(72)));content.addView(gap(8));}
    void item(String h,String v){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(15),dp(10),dp(15),dp(10));x.setBackground(box(white,18));TextView a=tv(h,13,muted);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(a);x.addView(tv(v,16,navy));content.addView(x,new LinearLayout.LayoutParams(-1,dp(70)));content.addView(gap(8));}
    void menu(String s,String icon,String page){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(9),0,dp(9),0);x.setBackground(box(Color.rgb(246,249,250),16));x.addView(tv(icon,21,teal),new LinearLayout.LayoutParams(dp(42),dp(50)));TextView t=tv(s,15,navy);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));x.setOnClickListener(v->{drawer.setVisibility(View.GONE);if(page.equals("login")){session="";role="";history.clear();showLogin();}else open(page);});drawer.addView(x,new LinearLayout.LayoutParams(-1,dp(50)));drawer.addView(gap(7));}
    void drawerHead(String roleName){drawer.removeAllViews();LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(17),dp(15),dp(17),dp(15));h.setBackground(gradient(navy,teal,20));h.addView(tv("ساختمان‌یار",21,white));h.addView(tv(roleName,12,Color.rgb(210,230,230)));drawer.addView(h,new LinearLayout.LayoutParams(-1,dp(86)));drawer.addView(gap(13));}
    void managerDrawer(){drawerHead("مدیریت ساختمان");menu("داشبورد","⌂","manager");menu("واحدها و ساکنان","▣","units");menu("شارژ و هزینه‌ها","₮","charges");menu("تعمیرات","⚒","repairs");menu("پرداخت‌ها","✓","payments");menu("اشتراک سامانه","★","plans");menu("خروج","↪","login");}
    void residentDrawer(){drawerHead("حساب شخصی ساکن");menu("داشبورد من","⌂","resident");menu("ثبت پرداخت","₮","resident_pay");menu("خروج","↪","login");}
    void adminDrawer(){drawerHead("مدیریت کل سامانه");menu("داشبورد کل","⌂","admin");menu("ساختمان‌ها","▣","admin_buildings");menu("اشتراک‌ها","★","admin_plans");menu("تنظیمات","⚙","admin_settings");menu("خروج","↪","login");}

    void login(String u,String p,String r){if(u.isEmpty()||p.isEmpty()){toast("نام کاربری و رمز عبور را وارد کنید");return;}final int t=token;io.submit(()->{try{JSONObject b=new JSONObject().put("action",r.equals("resident")?"login_resident":"login_manager").put("username",u).put("password",p);JSONObject j=new JSONObject(post(b,null));if(j.has("error"))throw new Exception(j.getString("error"));session=j.getString("session");role=r;history.clear();history.addLast(r.equals("resident")?"resident":"manager");runOnUiThread(()->{if(t!=token)return;if(r.equals("resident"))residentHome();else managerHome();});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
    void register(){frame("ثبت ساختمان",true);section("ساختمان جدید بسازید","اطلاعات مدیر و ساختمان را وارد کنید");EditText n=input("نام ساختمان"),a=input("آدرس ساختمان"),u=input("نام کاربری مدیر"),p=input("رمز عبور");p.setInputType(129);for(EditText e:new EditText[]{n,a,u,p}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ثبت و ورود به پنل",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(v->io.submit(()->{try{JSONObject j=new JSONObject().put("action","register_manager").put("building_name",n.getText().toString()).put("address",a.getText().toString()).put("username",u.getText().toString()).put("password",p.getText().toString());JSONObject z=new JSONObject(post(j,null));if(z.has("error"))throw new Exception(z.getString("error"));session=z.getString("session");role="manager";history.clear();history.addLast("manager");runOnUiThread(this::managerHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));}

    void managerHome(){frame("داشبورد مدیر",false);managerDrawer();hero("سلام، مدیر ساختمان 👋","وضعیت ساختمان و کارهای مهم را از همین‌جا مدیریت کنید.",teal);section("خلاصه امروز","دسترسی سریع به بخش‌های اصلی");action("واحدها و ساکنان","واحدها، ساکنان و حساب‌ها","▣","units",teal);action("شارژ و هزینه‌ها","ثبت و مدیریت هزینه‌های ساختمان","₮","charges",gold);action("تعمیرات","ثبت و پیگیری هزینه تعمیرات","⚒","repairs",blue);action("پرداخت‌ها","بررسی و تأیید پرداخت‌های ساکنان","✓","payments",green);section("اشتراک","وضعیت سرویس ساختمان");action("اشتراک سامانه","مشاهده طرح‌ها و درخواست اشتراک","★","plans",teal);}
    void units(){frame("واحدها و ساکنان",true);managerDrawer();section("مدیریت واحدها","لیست واحدهای ثبت‌شده");Button add=btn("＋ افزودن واحد جدید",teal);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));add.setOnClickListener(v->addUnit());call("dashboard",j->{JSONArray a=j.optJSONArray("units");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item("واحد "+x.optString("unit_no"),"تعداد ساکنان: "+x.optInt("resident_count"));}});}
    void addUnit(){frame("افزودن واحد",true);section("واحد جدید","اطلاعات واحد را وارد کنید");EditText n=input("شماره واحد"),r=input("تعداد ساکنان"),o=input("نام مالک / ساکن");for(EditText e:new EditText[]{n,r,o}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ذخیره واحد",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->callObj(new JSONObject().put("action","add_unit").put("unit_no",n.getText().toString()).put("residents_count",r.getText().toString()).put("resident_name",o.getText().toString()),j->{toast("واحد ثبت شد");open("units");}));}
    void charges(){frame("شارژ و هزینه‌ها",true);managerDrawer();section("هزینه‌های ساختمان","ثبت و مشاهده هزینه‌ها");Button b=btn("＋ ثبت هزینه جدید",gold);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));b.setOnClickListener(v->addCharge());call("dashboard",j->{JSONArray a=j.optJSONArray("charges");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("title","هزینه"),money(x.optDouble("amount_rial")));}});}
    void addCharge(){frame("ثبت هزینه",true);section("هزینه جدید","مبلغ را به تومان وارد کنید");EditText t=input("عنوان هزینه"),a=input("مبلغ به تومان"),d=input("توضیحات");for(EditText e:new EditText[]{t,a,d}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ثبت هزینه",gold);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long q=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_charge").put("title",t.getText().toString()).put("amount_rial",q).put("description",d.getText().toString()),j->{toast("هزینه ثبت شد");open("charges");});}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void repairs(){frame("تعمیرات",true);managerDrawer();section("تعمیرات ساختمان","هزینه‌های تعمیر و نگهداری");Button b=btn("＋ ثبت تعمیر جدید",blue);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));b.setOnClickListener(v->addRepair());call("dashboard",j->{JSONArray a=j.optJSONArray("repairs");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("title","تعمیر"),money(x.optDouble("amount")));}});}
    void addRepair(){frame("ثبت تعمیر",true);section("تعمیر جدید","اطلاعات هزینه تعمیر را وارد کنید");EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات");for(EditText e:new EditText[]{t,a,d}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ثبت تعمیر",blue);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long q=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString()).put("amount_rial",q).put("description",d.getText().toString()),j->{toast("تعمیر ثبت شد");open("repairs");});}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void payments(){frame("پرداخت‌ها",true);managerDrawer();section("پرداخت‌های ساکنان","پرداخت‌های ثبت‌شده را بررسی کنید");call("dashboard",j->{JSONArray a=j.optJSONArray("payments");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item("پرداخت واحد "+x.optString("unit_id"),money(x.optDouble("amount"))+"  •  "+x.optString("status"));}});}
    void plans(){frame("اشتراک سامانه",true);managerDrawer();section("طرح‌های اشتراک","طرح مناسب ساختمان را انتخاب کنید");call("list_plans",j->{JSONArray a=j.optJSONArray("data");if(a==null)a=j.optJSONArray("plans");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name"),money(x.optDouble("price_rial"))+"  •  "+x.optInt("duration_days")+" روز");}});}
    void residentHome(){frame("داشبورد ساکن",false);residentDrawer();hero("سلام 👋","وضعیت مالی واحد شما در یک نگاه.",blue);call("dashboard",j->{JSONObject u=j.optJSONObject("unit");stat("واحد من",u==null?"-":u.optString("unit_no"),blue);JSONArray p=j.optJSONArray("payments"),c=j.optJSONArray("charges");stat("پرداخت‌های ثبت‌شده",String.valueOf(p==null?0:p.length()),green);stat("هزینه‌ها",String.valueOf(c==null?0:c.length()),gold);});action("ثبت پرداخت","ارسال رسید/پرداخت برای بررسی مدیر","₮","resident_pay",teal);}
    void residentPay(){frame("ثبت پرداخت",true);residentDrawer();section("پرداخت جدید","مبلغ را به تومان وارد کنید");EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات");for(EditText e:new EditText[]{a,n}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ارسال برای تأیید مدیر",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long q=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_payment").put("amount_rial",q).put("note",n.getText().toString()),j->toast("پرداخت ثبت شد و پس از تأیید مدیر اعمال می‌شود"));}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void adminHome(){frame("مدیرکل سامانه",false);adminDrawer();hero("مرکز کنترل سامانه 🔐","ساختمان‌ها، اشتراک‌ها و تنظیمات را مدیریت کنید.",Color.rgb(88,70,164));call("admin_dashboard",j->{JSONArray b=j.optJSONArray("buildings"),p=j.optJSONArray("plans"),r=j.optJSONArray("requests");stat("ساختمان‌های ثبت‌شده",String.valueOf(b==null?0:b.length()),teal);stat("طرح‌های اشتراک",String.valueOf(p==null?0:p.length()),blue);stat("درخواست‌های اشتراک",String.valueOf(r==null?0:r.length()),r!=null&&r.length()>0?gold:green);});section("مدیریت کل","ابزارهای اصلی مدیر سامانه");action("مدیریت ساختمان‌ها","وضعیت و مشخصات ساختمان‌ها","▣","admin_buildings",teal);action("مدیریت اشتراک‌ها","طرح‌ها و درخواست‌های اشتراک","★","admin_plans",blue);action("تنظیمات سامانه","نام برنامه، آزمایشی و درگاه","⚙","admin_settings",navy);}
    void adminBuildings(){frame("مدیریت ساختمان‌ها",true);adminDrawer();section("ساختمان‌های ثبت‌شده","وضعیت اشتراک ساختمان‌ها");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("buildings");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name","بدون نام"),"وضعیت: "+x.optString("subscription_status"));}});}
    void adminPlans(){frame("مدیریت اشتراک‌ها",true);adminDrawer();section("طرح‌های اشتراک","طرح‌ها و درخواست‌های ثبت‌شده");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("plans");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name","طرح"),money(x.optDouble("price_rial"))+"  •  "+x.optInt("duration_days")+" روز");}JSONArray r=j.optJSONArray("requests");if(r!=null&&r.length()>0){section("درخواست‌ها","درخواست‌های در انتظار بررسی");for(int i=0;i<r.length();i++){JSONObject x=r.optJSONObject(i);item("درخواست "+x.optString("id"),"وضعیت: "+x.optString("status"));}}});}
    void adminSettings(){frame("تنظیمات سامانه",true);adminDrawer();section("تنظیمات فعلی","پارامترهای اصلی سامانه");call("admin_dashboard",j->{JSONObject x=j.optJSONObject("settings");if(x!=null){item("نام برنامه",x.optString("app_name"));item("دوره آزمایشی",x.optString("free_trial_days")+" روز");item("تأیید ایمیل",x.optBoolean("email_verification_enabled")?"فعال":"غیرفعال");item("درگاه پرداخت",x.optBoolean("payment_gateway_enabled")?"فعال":"غیرفعال");}});}

    void call(String action,final Handler h){final int t=token;io.submit(()->{try{JSONObject j=new JSONObject(post(new JSONObject().put("action",action),session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{if(t!=token)return;try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{if(t==token)toast(e.getMessage()==null?"خطا در دریافت اطلاعات":e.getMessage());});}});}
    void callObj(JSONObject b,final Handler h){final int t=token;io.submit(()->{try{JSONObject j=new JSONObject(post(b,session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{if(t!=token)return;try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{if(t==token)toast(e.getMessage()==null?"خطا در ارتباط با سامانه":e.getMessage());});}});}
    String post(JSONObject b,String tok)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(tok!=null&&!tok.isEmpty())c.setRequestProperty("Authorization","Bearer "+tok);c.getOutputStream().write(b.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();java.io.InputStream is=code<400?c.getInputStream():c.getErrorStream();java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=is.read(buf))!=-1)out.write(buf,0,n);String s=new String(out.toByteArray(),StandardCharsets.UTF_8);if(code>=400){try{JSONObject e=new JSONObject(s);if(e.has("error"))throw new Exception(e.getString("error"));}catch(JSONException ignored){}throw new Exception("خطای ارتباط با سرور ("+code+")");}return s;}
    String money(double rial){return String.format(Locale.US,"%.0f تومان",rial/10.0);}
    void toast(String s){Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_LONG).show();}
    interface Handler{void handle(JSONObject j)throws Exception;}
}
