package com.sakhtemanyar;

import android.app.*;
import android.os.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api";
    LinearLayout root,content,drawer; FrameLayout shell; TextView title; String session="",role=""; final ArrayDeque<String> history=new ArrayDeque<>();
    final ExecutorService io=Executors.newSingleThreadExecutor(); int viewToken=0;
    int navy=Color.rgb(8,24,40),teal=Color.rgb(8,145,145),mint=Color.rgb(224,248,246),bg=Color.rgb(246,249,251),white=Color.WHITE,text=Color.rgb(24,39,54),muted=Color.rgb(105,121,135),orange=Color.rgb(238,151,48),red=Color.rgb(210,76,76);
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(14),dp(7),dp(14),dp(7));return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(white);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(box(teal,16));b.setPadding(dp(8),0,dp(8),0);return b;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setTextColor(text);e.setHintTextColor(Color.rgb(150,160,170));e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setPadding(dp(15),0,dp(15),0);e.setSingleLine(true);e.setBackground(box(white,15));return e;}
    Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    void frame(String page,boolean inner){viewToken++;root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(8),dp(7),dp(8),dp(7));bar.setBackgroundColor(navy);TextView nav=tv(inner?"‹":"☰",30,white);nav.setGravity(Gravity.CENTER);bar.addView(nav,new LinearLayout.LayoutParams(dp(52),dp(48)));title=tv(page,18,white);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(62)));shell=new FrameLayout(this);root.addView(shell,new LinearLayout.LayoutParams(-1,0,1));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(30));content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content);shell.addView(sv,new FrameLayout.LayoutParams(-1,-1));drawer=new LinearLayout(this);drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(dp(16),dp(18),dp(16),dp(18));drawer.setBackgroundColor(white);drawer.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);shell.addView(drawer,new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.86),-1,Gravity.RIGHT));drawer.setVisibility(View.GONE);nav.setOnClickListener(v->{if(inner)backPage();else toggleDrawer();});}
    void toggleDrawer(){if(drawer!=null)drawer.setVisibility(drawer.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);}
    void open(String id){if(history.isEmpty()||!history.peekLast().equals(id))history.addLast(id);show(id);}
    void show(String id){if(id.equals("manager"))managerHome();else if(id.equals("units"))units();else if(id.equals("charges"))charges();else if(id.equals("repairs"))repairs();else if(id.equals("payments"))payments();else if(id.equals("plans"))plans();else if(id.equals("resident"))residentHome();else if(id.equals("resident_pay"))residentPay();else if(id.equals("admin"))adminHome();else if(id.equals("admin_buildings"))adminBuildings();else if(id.equals("admin_plans"))adminPlans();else if(id.equals("admin_settings"))adminSettings();else showLogin();}
    void backPage(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){history.removeLast();show(history.peekLast());}else{session="";role="";history.clear();showLogin();}}
    @Override public void onBackPressed(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){backPage();return;}if(!role.isEmpty()){session="";role="";history.clear();showLogin();return;}super.onBackPressed();}
    void hero(String a,String b){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(18),dp(17),dp(18),dp(17));h.setBackground(box(navy,24));TextView x=tv(a,21,white);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(x);h.addView(tv(b,13,Color.rgb(194,214,224)));content.addView(h,new LinearLayout.LayoutParams(-1,dp(108)));content.addView(gap(14));}
    void titleRow(String s){TextView t=tv(s,17,navy);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(t,new LinearLayout.LayoutParams(-1,dp(42)));}
    void info(String label,String value,int accent){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(11),dp(15),dp(11));c.setBackground(box(white,20));TextView a=tv(label,12,muted);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(a);TextView b=tv(value,18,accent);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(b);content.addView(c,new LinearLayout.LayoutParams(-1,dp(82)));content.addView(gap(9));}
    void action(String label,String sub,String icon,String page){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),0,dp(10),0);c.setBackground(box(white,19));TextView ic=tv(icon,25,teal);ic.setGravity(Gravity.CENTER);c.addView(ic,new LinearLayout.LayoutParams(dp(52),dp(62)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(label,15,navy));tx.addView(tv(sub,11,muted));c.addView(tx,new LinearLayout.LayoutParams(0,dp(62),1));TextView ar=tv("‹",25,muted);ar.setGravity(Gravity.CENTER);c.addView(ar,new LinearLayout.LayoutParams(dp(35),dp(62)));c.setOnClickListener(v->open(page));content.addView(c,new LinearLayout.LayoutParams(-1,dp(70)));content.addView(gap(9));}
    void item(String h,String v){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(10),dp(15),dp(10));c.setBackground(box(white,18));TextView a=tv(h,13,muted);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(a);c.addView(tv(v,16,navy));content.addView(c,new LinearLayout.LayoutParams(-1,dp(70)));content.addView(gap(8));}
    void menuItem(String s,String ic,String page){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),0,dp(10),0);r.setBackground(box(Color.rgb(245,248,250),16));r.addView(tv(ic,21,teal),new LinearLayout.LayoutParams(dp(44),dp(52)));TextView n=tv(s,15,navy);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(n,new LinearLayout.LayoutParams(0,dp(52),1));r.setOnClickListener(v->{drawer.setVisibility(View.GONE);if(page.equals("login")){session="";role="";history.clear();showLogin();}else open(page);});drawer.addView(r,new LinearLayout.LayoutParams(-1,dp(52)));drawer.addView(gap(8));}
    void drawerHead(String roleName){drawer.removeAllViews();LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(16),dp(14),dp(16),dp(14));h.setBackground(box(navy,20));h.addView(tv("ساختمان‌یار",20,white));h.addView(tv(roleName,12,Color.rgb(194,214,224)));drawer.addView(h,new LinearLayout.LayoutParams(-1,dp(90)));drawer.addView(gap(14));}
    void managerDrawer(){drawerHead("پنل مدیریت ساختمان");menuItem("داشبورد","⌂","manager");menuItem("واحدها و ساکنان","▣","units");menuItem("شارژ و هزینه‌ها","₮","charges");menuItem("تعمیرات","⚒","repairs");menuItem("پرداخت‌ها","✓","payments");menuItem("اشتراک سامانه","★","plans");menuItem("خروج","↪","login");}
    void residentDrawer(){drawerHead("پنل ساکن");menuItem("داشبورد من","⌂","resident");menuItem("ثبت پرداخت","₮","resident_pay");menuItem("خروج","↪","login");}
    void adminDrawer(){drawerHead("پنل مدیرکل سامانه");menuItem("داشبورد کل سامانه","⌂","admin");menuItem("مدیریت ساختمان‌ها","▣","admin_buildings");menuItem("مدیریت اشتراک‌ها","★","admin_plans");menuItem("تنظیمات سامانه","⚙","admin_settings");menuItem("خروج","↪","login");}
    void showLogin(){role="";session="";history.clear();frame("ورود به ساختمان‌یار",false);content.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(gap(20));TextView logo=tv("ساختمان‌یار",31,teal);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(logo,new LinearLayout.LayoutParams(-1,dp(55)));TextView sub=tv("مدیریت ساده، شفاف و هوشمند ساختمان",14,muted);sub.setGravity(Gravity.CENTER);content.addView(sub);content.addView(gap(22));EditText u=input("نام کاربری"),p=input("رمز عبور");p.setInputType(129);content.addView(u,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));content.addView(p,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(15));Button m=btn("ورود به پنل مدیر ساختمان"),r=btn("ورود به پنل ساکن"),a=btn("ورود به پنل مدیرکل سامانه"),reg=btn("ثبت ساختمان و مدیر جدید");content.addView(m,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(8));content.addView(r,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(8));content.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(8));content.addView(reg,new LinearLayout.LayoutParams(-1,dp(54)));m.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"manager"));r.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"resident"));a.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"admin"));reg.setOnClickListener(v->register());}
    void login(String u,String p,String r){if(u.isEmpty()||p.isEmpty()){toast("نام کاربری و رمز عبور را وارد کنید");return;}int token=viewToken;io.submit(()->{try{JSONObject b=new JSONObject().put("action",r.equals("admin")?"admin_login":r.equals("resident")?"login_resident":"login_manager").put("username",u).put("password",p);JSONObject j=new JSONObject(post(b,null));if(j.has("error"))throw new Exception(j.getString("error"));session=j.getString("session");role=r;history.clear();history.addLast(r.equals("admin")?"admin":r.equals("resident")?"resident":"manager");runOnUiThread(()->{if(token!=viewToken)return;if(r.equals("admin"))adminHome();else if(r.equals("resident"))residentHome();else managerHome();});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
    void register(){frame("ثبت مدیر و ساختمان",true);EditText n=input("نام ساختمان"),ad=input("آدرس ساختمان"),u=input("نام کاربری مدیر"),p=input("رمز عبور");p.setInputType(129);form(n,ad,u,p);Button b=btn("ثبت ساختمان و ورود");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->io.submit(()->{try{JSONObject j=new JSONObject().put("action","register_manager").put("building_name",n.getText().toString()).put("address",ad.getText().toString()).put("username",u.getText().toString()).put("password",p.getText().toString());JSONObject z=new JSONObject(post(j,null));if(z.has("error"))throw new Exception(z.getString("error"));session=z.getString("session");role="manager";history.clear();history.addLast("manager");runOnUiThread(this::managerHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));}
    void form(EditText... e){for(EditText x:e){content.addView(x,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}}
    void managerHome(){frame("داشبورد مدیر ساختمان",false);managerDrawer();hero("سلام مدیر ساختمان 👋","اینجا وضعیت کلی ساختمان را یکجا می‌بینید.");titleRow("دسترسی سریع");action("واحدها و ساکنان","مدیریت واحدها و اطلاعات ساکنان","▣","units");action("شارژ و هزینه‌ها","ثبت و مشاهده هزینه‌های ساختمان","₮","charges");action("تعمیرات","ثبت و پیگیری تعمیرات","⚒","repairs");action("پرداخت‌ها","مشاهده و تأیید پرداخت‌ها","✓","payments");}
    void units(){frame("واحدها و ساکنان",true);managerDrawer();titleRow("واحدهای ساختمان");Button add=btn("＋ افزودن واحد جدید");content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));add.setOnClickListener(v->addUnit());call("dashboard",j->{JSONArray a=j.optJSONArray("units");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item("واحد "+x.optString("unit_no"),"تعداد ساکنان: "+x.optInt("resident_count"));}});}
    void addUnit(){frame("افزودن واحد",true);EditText n=input("شماره واحد"),r=input("تعداد ساکنان"),o=input("نام مالک / ساکن");form(n,r,o);Button b=btn("ذخیره واحد");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->callObj(new JSONObject().put("action","add_unit").put("unit_no",n.getText().toString()).put("residents_count",r.getText().toString()).put("resident_name",o.getText().toString()),j->{toast("واحد با موفقیت ثبت شد");open("units");}));}
    void charges(){frame("شارژ و هزینه‌ها",true);managerDrawer();titleRow("هزینه‌های ساختمان");Button b=btn("＋ ثبت هزینه جدید");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));b.setOnClickListener(v->addCharge());call("dashboard",j->{JSONArray a=j.optJSONArray("charges");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("title","هزینه"),money(x.optDouble("amount_rial")));}});}
    void addCharge(){frame("ثبت هزینه جدید",true);EditText t=input("عنوان هزینه"),a=input("مبلغ به تومان"),d=input("توضیحات");form(t,a,d);Button b=btn("ثبت هزینه");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long amount=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_charge").put("title",t.getText().toString()).put("amount_rial",amount).put("description",d.getText().toString()),j->{toast("هزینه ثبت شد");open("charges");});}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void repairs(){frame("تعمیرات",true);managerDrawer();titleRow("تعمیرات ساختمان");Button b=btn("＋ ثبت تعمیر جدید");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));b.setOnClickListener(v->addRepair());call("dashboard",j->{JSONArray a=j.optJSONArray("repairs");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("title","تعمیر"),money(x.optDouble("amount")));}});}
    void addRepair(){frame("ثبت تعمیر جدید",true);EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات");form(t,a,d);Button b=btn("ثبت تعمیر");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long amount=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString()).put("amount_rial",amount).put("description",d.getText().toString()),j->{toast("تعمیر ثبت شد");open("repairs");});}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void payments(){frame("پرداخت‌ها",true);managerDrawer();titleRow("پرداخت‌های ثبت‌شده");call("dashboard",j->{JSONArray a=j.optJSONArray("payments");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item("پرداخت واحد "+x.optString("unit_id"),money(x.optDouble("amount"))+"  •  وضعیت: "+x.optString("status"));}});}
    void plans(){frame("اشتراک سامانه",true);managerDrawer();titleRow("طرح‌های فعال");call("list_plans",j->{JSONArray a=j.optJSONArray("data");if(a==null)a=j.optJSONArray("plans");if(a==null&&j.toString().startsWith("["))return;if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name"),money(x.optDouble("price_rial"))+" / "+x.optInt("duration_days")+" روز");}});}
    void residentHome(){frame("داشبورد ساکن",false);residentDrawer();hero("پنل شخصی من","فقط اطلاعات مالی واحد خودتان در این بخش نمایش داده می‌شود.");call("dashboard",j->{org.json.JSONObject u=j.optJSONObject("unit");info("واحد من",u==null?"-":u.optString("unit_no"),teal);JSONArray p=j.optJSONArray("payments");info("تعداد پرداخت‌ها",String.valueOf(p==null?0:p.length()),teal);JSONArray c=j.optJSONArray("charges");info("تعداد هزینه‌ها",String.valueOf(c==null?0:c.length()),orange);});action("ثبت پرداخت","ارسال پرداخت برای بررسی مدیر","₮","resident_pay");}
    void residentPay(){frame("ثبت پرداخت",true);residentDrawer();titleRow("پرداخت بدهی واحد");EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات");form(a,n);Button b=btn("ارسال پرداخت برای تأیید");content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->{try{long amount=Long.parseLong(a.getText().toString().trim())*10;callObj(new JSONObject().put("action","add_payment").put("amount_rial",amount).put("note",n.getText().toString()),j->toast("پرداخت ثبت شد و پس از تأیید مدیر در حساب اعمال می‌شود"));}catch(Exception e){toast("مبلغ نامعتبر است");}});}
    void adminHome(){frame("مدیرکل سامانه",false);adminDrawer();hero("پنل مدیرکل سامانه 🔐","کنترل کامل ساختمان‌ها، اشتراک‌ها و تنظیمات سامانه.");titleRow("وضعیت سامانه");call("admin_dashboard",j->{JSONArray b=j.optJSONArray("buildings"),p=j.optJSONArray("plans"),r=j.optJSONArray("requests");info("ساختمان‌ها",String.valueOf(b==null?0:b.length()),teal);info("طرح‌های اشتراک",String.valueOf(p==null?0:p.length()),teal);info("درخواست‌های در انتظار",String.valueOf(r==null?0:r.length()),r!=null&&r.length()>0?orange:teal);});titleRow("مدیریت");action("ساختمان‌ها","مشاهده وضعیت اشتراک ساختمان‌ها","▣","admin_buildings");action("اشتراک‌ها","مشاهده طرح‌ها و قیمت‌ها","★","admin_plans");action("تنظیمات سامانه","نام برنامه، آزمایشی و درگاه","⚙","admin_settings");}
    void adminBuildings(){frame("مدیریت ساختمان‌ها",true);adminDrawer();titleRow("لیست ساختمان‌ها");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("buildings");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name","بدون نام"),"وضعیت اشتراک: "+x.optString("subscription_status"));}});}
    void adminPlans(){frame("مدیریت اشتراک‌ها",true);adminDrawer();titleRow("طرح‌های اشتراک");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("plans");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name","طرح"),money(x.optDouble("price_rial"))+"  •  "+x.optInt("duration_days")+" روز");}JSONArray r=j.optJSONArray("requests");if(r!=null&&r.length()>0){titleRow("درخواست‌های اشتراک");for(int i=0;i<r.length();i++){JSONObject x=r.optJSONObject(i);item("درخواست "+x.optString("id"),"وضعیت: "+x.optString("status"));}}});}
    void adminSettings(){frame("تنظیمات سامانه",true);adminDrawer();titleRow("تنظیمات فعلی");call("admin_dashboard",j->{org.json.JSONObject x=j.optJSONObject("settings");if(x!=null){item("نام برنامه",x.optString("app_name"));item("دوره آزمایشی",x.optString("free_trial_days")+" روز");item("تأیید ایمیل",x.optBoolean("email_verification_enabled")?"فعال":"غیرفعال");item("درگاه پرداخت",x.optBoolean("payment_gateway_enabled")?"فعال":"غیرفعال");}});}
    void call(String action,final Handler h){final int token=viewToken;io.submit(()->{try{JSONObject j=new JSONObject(post(new JSONObject().put("action",action),session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{if(token!=viewToken)return;try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{if(token==viewToken)toast(e.getMessage()==null?"خطا در دریافت اطلاعات":e.getMessage());});}});}
    void callObj(JSONObject b,final Handler h){final int token=viewToken;io.submit(()->{try{JSONObject j=new JSONObject(post(b,session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{if(token!=viewToken)return;try{h.handle(j);}catch(Exception e){toast(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{if(token==viewToken)toast(e.getMessage()==null?"خطا در ارتباط با سامانه":e.getMessage());});}});}
    String post(JSONObject b,String tok)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(8000);c.setReadTimeout(10000);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(tok!=null&&!tok.isEmpty())c.setRequestProperty("Authorization","Bearer "+tok);c.getOutputStream().write(b.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();java.io.InputStream is=code<400?c.getInputStream():c.getErrorStream();java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=is.read(buf))!=-1)out.write(buf,0,n);String s=new String(out.toByteArray(),StandardCharsets.UTF_8);if(code>=400){try{JSONObject e=new JSONObject(s);if(e.has("error"))throw new Exception(e.getString("error"));}catch(org.json.JSONException ignored){}throw new Exception("خطای ارتباط با سرور ("+code+")");}return s;}
    String money(double rial){return String.format(Locale.US,"%.0f تومان",rial/10.0);}
    void toast(String s){Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_LONG).show();}
    interface Handler{void handle(JSONObject j)throws Exception;}
}
