package com.sakhtemanyar;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String API="https://okizneyesdwiundvadpe.supabase.co/functions/v1/api";
    LinearLayout root,content,drawer; String session="",role=""; final ArrayDeque<String> history=new ArrayDeque<>();
    final ExecutorService io=Executors.newSingleThreadExecutor(); int screenToken=0;
    final int navy=Color.rgb(8,25,42), navy2=Color.rgb(12,52,67), teal=Color.rgb(0,153,145), teal2=Color.rgb(39,193,177), blue=Color.rgb(66,112,195), green=Color.rgb(40,157,105), gold=Color.rgb(218,151,42), red=Color.rgb(207,70,79), bg=Color.rgb(246,249,251), white=Color.WHITE, text=Color.rgb(25,38,52), muted=Color.rgb(105,120,133);
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    GradientDrawable grad(int a,int b,float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(14),dp(6),dp(14),dp(6));return t;}
    EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(15);e.setTextColor(text);e.setHintTextColor(Color.rgb(145,157,168));e.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);e.setSingleLine(true);e.setPadding(dp(15),0,dp(15),0);e.setBackground(box(white,16));return e;}
    Button btn(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(white);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setGravity(Gravity.CENTER);b.setBackground(box(c,16));b.setPadding(dp(7),0,dp(7),0);return b;}
    Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    @Override public void onBackPressed(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){history.removeLast();show(history.peekLast());return;}if(!role.isEmpty()){logout();return;}super.onBackPressed();}
    void frame(String title,boolean inner){screenToken++;root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(9),dp(7),dp(9),dp(7));bar.setBackground(grad(navy,navy2,0));TextView nav=tv(inner?"‹":"☰",31,white);nav.setGravity(Gravity.CENTER);bar.addView(nav,new LinearLayout.LayoutParams(dp(52),dp(50)));TextView t=tv(title,18,white);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));TextView brand=tv("ساختمان‌یار",12,Color.rgb(190,224,220));brand.setGravity(Gravity.CENTER);bar.addView(brand,new LinearLayout.LayoutParams(dp(92),dp(50)));root.addView(bar,new LinearLayout.LayoutParams(-1,dp(66)));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(32));content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));drawer=new LinearLayout(this);drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(dp(14),dp(16),dp(14),dp(22));drawer.setBackgroundColor(white);drawer.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(drawer,new LinearLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.86),-1));drawer.setVisibility(View.GONE);nav.setOnClickListener(v->{if(inner)backPage();else toggleDrawer();});}
    void toggleDrawer(){if(drawer!=null)drawer.setVisibility(drawer.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);}
    void open(String id){if(history.isEmpty()||!history.peekLast().equals(id))history.addLast(id);show(id);}
    void show(String id){if("manager".equals(id))managerHome();else if("units".equals(id))units();else if("charges".equals(id))charges();else if("repairs".equals(id))repairs();else if("payments".equals(id))payments();else if("plans".equals(id))plans();else if("resident".equals(id))residentHome();else if("resident_pay".equals(id))residentPay();else if("admin".equals(id))adminHome();else if("admin_buildings".equals(id))adminBuildings();else if("admin_plans".equals(id))adminPlans();else if("admin_settings".equals(id))adminSettings();else showLogin();}
    void backPage(){if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}if(history.size()>1){history.removeLast();show(history.peekLast());}else logout();}
    void logout(){session="";role="";history.clear();showLogin();}
    void showLogin(){role="";session="";history.clear();frame("ورود",false);content.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(gap(8));LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);hero.setPadding(dp(22),dp(22),dp(22),dp(22));hero.setBackground(grad(navy,teal,28));TextView logo=tv("ساختمان‌یار",31,white);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT,Typeface.BOLD);hero.addView(logo);TextView sub=tv("مدیریت ساختمان، شفاف و یکپارچه",14,Color.rgb(215,237,234));sub.setGravity(Gravity.CENTER);hero.addView(sub);content.addView(hero,new LinearLayout.LayoutParams(-1,dp(145)));content.addView(gap(20));TextView h=tv("ورود به حساب",23,navy);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h,new LinearLayout.LayoutParams(-1,dp(42)));content.addView(tv("نقش خود را انتخاب کنید",12,muted),new LinearLayout.LayoutParams(-1,dp(30)));EditText u=input("نام کاربری"),p=input("رمز عبور");p.setInputType(129);content.addView(u,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));content.addView(p,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(14));Button m=btn("ورود مدیر ساختمان  ›",teal),r=btn("ورود ساکن  ›",blue),a=btn("ورود مدیرکل سامانه  🔐",navy);content.addView(m,new LinearLayout.LayoutParams(-1,dp(55)));content.addView(gap(9));content.addView(r,new LinearLayout.LayoutParams(-1,dp(55)));content.addView(gap(9));content.addView(a,new LinearLayout.LayoutParams(-1,dp(52)));content.addView(gap(16));TextView q=tv("ساختمان هنوز در سامانه ثبت نشده؟",12,muted);q.setGravity(Gravity.CENTER);content.addView(q,new LinearLayout.LayoutParams(-1,dp(30)));Button reg=btn("＋ ثبت ساختمان و مدیر جدید",Color.rgb(86,106,119));content.addView(reg,new LinearLayout.LayoutParams(-1,dp(52)));m.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"manager"));r.setOnClickListener(v->login(u.getText().toString().trim(),p.getText().toString(),"resident"));a.setOnClickListener(v->startActivity(new Intent(this,AdminActivity.class)));reg.setOnClickListener(v->register());}
    void drawerHead(String title,String sub,int accent){drawer.removeAllViews();LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(17),dp(15),dp(17),dp(15));h.setBackground(grad(navy,accent,21));TextView a=tv("ساختمان‌یار",21,white);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(a);h.addView(tv(title,13,Color.rgb(218,235,234)));h.addView(tv(sub,11,Color.rgb(180,211,210)));drawer.addView(h,new LinearLayout.LayoutParams(-1,dp(101)));drawer.addView(gap(12));}
    void menu(String s,String icon,String page,int c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(9),0,dp(9),0);x.setBackground(box(Color.rgb(247,250,251),16));TextView i=tv(icon,21,c);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(dp(43),dp(50)));TextView t=tv(s,14,navy);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));x.addView(tv("‹",24,muted),new LinearLayout.LayoutParams(dp(30),dp(50)));x.setOnClickListener(v->{drawer.setVisibility(View.GONE);if("logout".equals(page))logout();else open(page);});drawer.addView(x,new LinearLayout.LayoutParams(-1,dp(50)));drawer.addView(gap(7));}
    void managerDrawer(){drawerHead("پنل مدیر ساختمان","مدیریت مالی، واحدها و عملیات ساختمان",teal);menu("داشبورد","⌂","manager",teal);menu("واحدها و ساکنان","▣","units",blue);menu("شارژ و هزینه‌ها","₮","charges",gold);menu("تعمیرات","⚒","repairs",red);menu("پرداخت‌ها","✓","payments",green);menu("اشتراک سامانه","★","plans",teal2);menu("خروج از حساب","↪","logout",red);}
    void residentDrawer(){drawerHead("حساب ساکن","اطلاعات مالی و پرداخت‌های من",blue);menu("داشبورد من","⌂","resident",blue);menu("ثبت پرداخت","₮","resident_pay",green);menu("خروج از حساب","↪","logout",red);}
    void adminDrawer(){drawerHead("مدیریت کل سامانه","کنترل ساختمان‌ها و اشتراک‌ها",Color.rgb(92,70,164));menu("داشبورد کل","⌂","admin",Color.rgb(92,70,164));menu("ساختمان‌ها","▣","admin_buildings",teal);menu("اشتراک‌ها","★","admin_plans",blue);menu("تنظیمات","⚙","admin_settings",navy);menu("خروج از حساب","↪","logout",red);}
    void hero(String title,String sub,int accent){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(19),dp(17),dp(19),dp(17));h.setBackground(grad(navy,accent,24));TextView a=tv(title,21,white);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.addView(a);h.addView(tv(sub,12,Color.rgb(215,232,232)));content.addView(h,new LinearLayout.LayoutParams(-1,dp(108)));content.addView(gap(13));}
    void section(String title,String sub){TextView a=tv(title,19,navy);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(a,new LinearLayout.LayoutParams(-1,dp(38)));if(sub!=null)content.addView(tv(sub,12,muted),new LinearLayout.LayoutParams(-1,dp(28)));}
    void stat(String l,String v,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(10),dp(14),dp(10));x.setBackground(box(white,18));x.addView(tv(l,11,muted));TextView z=tv(v,20,c);z.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(z);content.addView(x,new LinearLayout.LayoutParams(-1,dp(74)));content.addView(gap(8));}
    void statRow(String a,String av,String b,String bv){LinearLayout row=new LinearLayout(this);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);addStat(row,a,av,teal);addStat(row,b,bv,blue);content.addView(row,new LinearLayout.LayoutParams(-1,dp(84)));content.addView(gap(10));}
    void addStat(LinearLayout row,String l,String v,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(11),dp(7),dp(11),dp(7));x.setBackground(box(white,18));x.addView(tv(l,10,muted));TextView z=tv(v,18,c);z.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(z);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(76),1);lp.setMargins(dp(4),0,dp(4),0);row.addView(x,lp);}
    void action(String title,String sub,String icon,String page,int c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(8),dp(6),dp(8),dp(6));x.setBackground(box(white,19));TextView i=tv(icon,25,c);i.setGravity(Gravity.CENTER);i.setBackground(box(Color.rgb(241,247,247),15));x.addView(i,new LinearLayout.LayoutParams(dp(55),dp(58)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView a=tv(title,15,navy);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tx.addView(a);tx.addView(tv(sub,11,muted));x.addView(tx,new LinearLayout.LayoutParams(0,dp(58),1));x.addView(tv("‹",25,muted),new LinearLayout.LayoutParams(dp(31),dp(58)));x.setOnClickListener(v->open(page));content.addView(x,new LinearLayout.LayoutParams(-1,dp(70)));content.addView(gap(8));}
    void item(String h,String v){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(15),dp(10),dp(15),dp(10));x.setBackground(box(white,18));TextView a=tv(h,13,muted);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.addView(a);x.addView(tv(v,16,navy));content.addView(x,new LinearLayout.LayoutParams(-1,dp(70)));content.addView(gap(8));}
    void empty(String s){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setPadding(dp(15),dp(22),dp(15),dp(22));x.setBackground(box(white,20));TextView i=tv("○",36,teal);i.setGravity(Gravity.CENTER);x.addView(i,new LinearLayout.LayoutParams(-1,dp(50)));TextView t=tv(s,14,muted);t.setGravity(Gravity.CENTER);x.addView(t,new LinearLayout.LayoutParams(-1,dp(44)));content.addView(x,new LinearLayout.LayoutParams(-1,dp(125)));}
    void login(String u,String p,String r){if(u.isEmpty()||p.isEmpty()){toast("نام کاربری و رمز عبور را وارد کنید");return;}final int t=screenToken;io.submit(()->{try{JSONObject b=new JSONObject().put("action",r.equals("resident")?"login_resident":"login_manager").put("username",u).put("password",p);JSONObject j=new JSONObject(post(b,null));if(j.has("error"))throw new Exception(j.getString("error"));session=j.getString("session");role=r;history.clear();history.addLast(r.equals("resident")?"resident":"manager");runOnUiThread(()->{if(t!=screenToken)return;if("resident".equals(r))residentHome();else managerHome();});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}});}
    void register(){frame("ثبت ساختمان",true);section("شروع کار با ساختمان‌یار","ساختمان و حساب مدیر را یکجا بسازید");EditText n=input("نام ساختمان"),a=input("آدرس ساختمان"),u=input("نام کاربری مدیر"),p=input("رمز عبور حداقل ۶ کاراکتر");p.setInputType(129);for(EditText e:new EditText[]{n,a,u,p}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ثبت ساختمان و ورود",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(v->io.submit(()->{try{JSONObject j=new JSONObject().put("action","register_manager").put("building_name",n.getText().toString()).put("address",a.getText().toString()).put("username",u.getText().toString()).put("password",p.getText().toString());JSONObject z=new JSONObject(post(j,null));if(z.has("error"))throw new Exception(z.getString("error"));session=z.getString("session");role="manager";history.clear();history.addLast("manager");runOnUiThread(this::managerHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));}
    void managerHome(){frame("داشبورد مدیر",false);managerDrawer();hero("داشبورد ساختمان","امروز: "+JalaliDate.now()+"  •  همه تاریخ‌ها شمسی نمایش داده می‌شوند",teal);loadDashboard();}
    void loadDashboard(){call("dashboard",j->{JSONArray u=j.optJSONArray("units"),c=j.optJSONArray("charges"),p=j.optJSONArray("payments"),r=j.optJSONArray("repairs");statRow("واحدها",String.valueOf(u==null?0:u.length()),"تعمیرات",String.valueOf(r==null?0:r.length()));statRow("شارژها",String.valueOf(c==null?0:c.length()),"پرداخت‌ها",String.valueOf(p==null?0:p.length()));section("دسترسی سریع","مدیریت بخش‌های اصلی ساختمان");action("واحدها و ساکنان","ساخت واحد، ثبت ساکن و اطلاعات حساب","▣","units",blue);action("شارژ و هزینه‌ها","ثبت شارژ و هزینه ساختمان","₮","charges",gold);action("تعمیرات","ثبت و پیگیری هزینه تعمیرات","⚒","repairs",red);action("پرداخت‌ها","بررسی و تأیید پرداخت‌های ساکنان","✓","payments",green);action("اشتراک سامانه","مشاهده طرح‌ها و درخواست اشتراک","★","plans",teal2);});}
    void units(){frame("واحدها و ساکنان",true);managerDrawer();section("مدیریت واحدها","افزودن واحد و ساخت حساب ساکن");Button add=btn("＋ افزودن واحد",teal);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(11));add.setOnClickListener(v->addUnitDialog());call("dashboard",j->{JSONArray a=j.optJSONArray("units");if(a==null||a.length()==0){empty("هنوز واحدی ثبت نشده است");return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;unitCard(x);}});}
    void unitCard(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(12),dp(15),dp(12));c.setBackground(box(white,19));TextView n=tv("واحد "+x.optString("unit_no","-"),18,navy);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(n);c.addView(tv("مالک / ساکن: "+x.optString("owner_name","ثبت نشده"),12,muted));c.addView(tv("تعداد ساکنان: "+x.optString("resident_count","0"),12,muted));Button r=btn("＋ ساخت حساب ساکن",blue);c.addView(r,new LinearLayout.LayoutParams(-1,dp(46)));r.setOnClickListener(v->residentDialog(x.optString("id"),x.optString("unit_no")));content.addView(c,new LinearLayout.LayoutParams(-1,dp(145)));content.addView(gap(9));}
    void addUnitDialog(){final EditText no=input("شماره واحد"),cnt=input("تعداد ساکنان"),name=input("نام مالک / ساکن");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);l.addView(no,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));l.addView(cnt,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));l.addView(name,new LinearLayout.LayoutParams(-1,dp(54)));new AlertDialog.Builder(this).setTitle("افزودن واحد").setView(l).setNegativeButton("لغو",null).setPositiveButton("ذخیره",(d,w)->callObj(new JSONObject().put("action","add_unit").put("unit_no",no.getText().toString()).put("residents_count",cnt.getText().toString()).put("resident_name",name.getText().toString()),z->{toast("واحد ثبت شد");units();})).show();}
    void residentDialog(String unitId,String unitNo){final EditText n=input("نام و نام خانوادگی"),u=input("نام کاربری ساکن"),p=input("رمز عبور حداقل ۶ کاراکتر");p.setInputType(129);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{n,u,p}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("حساب ساکن • واحد "+unitNo).setView(l).setNegativeButton("لغو",null).setPositiveButton("ساخت حساب",(d,w)->callObj(new JSONObject().put("action","create_resident").put("unit_id",unitId).put("username",u.getText().toString()).put("password",p.getText().toString()).put("full_name",n.getText().toString()),z->toast("حساب ساکن ساخته شد"))).show();}
    void charges(){frame("شارژ و هزینه‌ها",true);managerDrawer();section("ثبت شارژ و هزینه","مبلغ به ریال ذخیره و در برنامه به تومان نمایش داده می‌شود");Button add=btn("＋ ثبت شارژ / هزینه",gold);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(12));add.setOnClickListener(v->chargeDialog());call("dashboard",j->{JSONArray a=j.optJSONArray("charges");if(a==null||a.length()==0){empty("هنوز شارژ یا هزینه‌ای ثبت نشده است");return;}section("سوابق ثبت‌شده",null);for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)item(x.optString("title","هزینه"),money(x.optDouble("amount_rial"))+"  •  "+JalaliDate.format(x.optString("created_at")));}});}
    void chargeDialog(){final EditText t=input("عنوان شارژ / هزینه"),a=input("مبلغ به تومان"),d=input("توضیحات");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("ثبت شارژ یا هزینه").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(x,w)->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);callObj(new JSONObject().put("action","add_charge").put("title",t.getText().toString()).put("amount_rial",rial).put("description",d.getText().toString()).put("allocation_method","per_unit"),z->{toast("هزینه ثبت شد");charges();});}).show();}
    void repairs(){frame("تعمیرات",true);managerDrawer();section("مدیریت تعمیرات","ثبت هزینه و نگهداری سوابق تعمیرات");Button add=btn("＋ ثبت تعمیر جدید",red);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(12));add.setOnClickListener(v->repairDialog());call("dashboard",j->{JSONArray a=j.optJSONArray("repairs");if(a==null||a.length()==0){empty("هنوز تعمیراتی ثبت نشده است");return;}section("سوابق تعمیرات",null);for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)item(x.optString("title","تعمیرات"),money(x.optDouble("amount"))+"  •  "+JalaliDate.format(x.optString("created_at")));}});}
    void repairDialog(){final EditText t=input("عنوان تعمیر"),a=input("هزینه به تومان"),d=input("توضیحات");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("ثبت تعمیر").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(x,w)->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString()).put("amount_rial",rial).put("description",d.getText().toString()),z->{toast("تعمیر ثبت شد");repairs();});}).show();}
    void payments(){frame("پرداخت‌ها",true);managerDrawer();section("کنترل پرداخت‌ها","پرداخت ساکن تا تأیید مدیر قطعی نمی‌شود");call("dashboard",j->{JSONArray a=j.optJSONArray("payments");if(a==null||a.length()==0){empty("پرداختی ثبت نشده است");return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)paymentCard(x);}});}
    void paymentCard(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(12),dp(15),dp(12));c.setBackground(box(white,19));TextView h=tv("پرداخت "+money(x.optDouble("amount")),17,navy);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(h);c.addView(tv("وضعیت: "+statusFa(x.optString("status")),12,statusColor(x.optString("status"))));c.addView(tv("تاریخ: "+JalaliDate.format(x.optString("created_at")),12,muted));if("pending".equals(x.optString("status"))){LinearLayout row=new LinearLayout(this);Button ok=btn("تأیید پرداخت",green),no=btn("رد پرداخت",red);row.addView(ok,new LinearLayout.LayoutParams(0,dp(48),1));row.addView(no,new LinearLayout.LayoutParams(0,dp(48),1));c.addView(row);ok.setOnClickListener(v->approvePayment(x.optString("id"),true));no.setOnClickListener(v->approvePayment(x.optString("id"),false));}content.addView(c,new LinearLayout.LayoutParams(-1,dp("pending".equals(x.optString("status"))?170:125)));content.addView(gap(9));}
    void approvePayment(String id,boolean ok){callObj(new JSONObject().put("action","approve_payment").put("payment_id",id).put("approved",ok),z->{toast(ok?"پرداخت تأیید شد":"پرداخت رد شد");payments();});}
    void plans(){frame("اشتراک سامانه",true);managerDrawer();section("طرح‌های اشتراک","دوره مناسب ساختمان را انتخاب و درخواست کنید");call("list_plans",j->{JSONArray a=j.optJSONArray("data");if(a==null||a.length()==0){empty("در حال حاضر طرح فعالی وجود ندارد");return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)planCard(x);}});}
    void planCard(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(13),dp(16),dp(13));c.setBackground(grad(Color.WHITE,Color.rgb(248,251,252),20));TextView h=tv(x.optString("name","طرح"),18,navy);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(h);c.addView(tv(money(x.optDouble("price_rial"))+"  •  "+x.optInt("duration_days")+" روز",13,teal));Button b=btn("درخواست این طرح",teal);c.addView(b,new LinearLayout.LayoutParams(-1,dp(47)));b.setOnClickListener(v->callObj(new JSONObject().put("action","request_subscription").put("plan_id",x.optString("id")),z->toast("درخواست اشتراک ثبت شد")));content.addView(c,new LinearLayout.LayoutParams(-1,dp(130)));content.addView(gap(9));}
    void residentHome(){frame("داشبورد ساکن",false);residentDrawer();hero("سلام 👋","امروز: "+JalaliDate.now()+"  •  وضعیت مالی واحد شما",blue);call("dashboard",j->{JSONObject u=j.optJSONObject("unit");JSONArray c=j.optJSONArray("charges"),p=j.optJSONArray("payments"),r=j.optJSONArray("repairs");statRow("واحد",u==null?"-":u.optString("unit_no","-"),"پرداخت‌ها",String.valueOf(p==null?0:p.length()));section("امور مالی من","مشاهده وضعیت و ثبت پرداخت");action("ثبت پرداخت","ثبت پرداخت برای بررسی مدیر","₮","resident_pay",green);if(c!=null&&c.length()>0){JSONObject x=c.optJSONObject(0);if(x!=null)item("آخرین شارژ",money(x.optDouble("amount_rial"))+"  •  "+JalaliDate.format(x.optString("created_at")));}if(p!=null&&p.length()>0){JSONObject x=p.optJSONObject(0);if(x!=null)item("آخرین پرداخت",statusFa(x.optString("status"))+"  •  "+money(x.optDouble("amount")));}if(r!=null&&r.length()>0){JSONObject x=r.optJSONObject(0);if(x!=null)item("آخرین تعمیر",x.optString("title","تعمیرات"));}});}
    void residentPay(){frame("ثبت پرداخت",true);residentDrawer();section("ثبت پرداخت جدید","پرداخت پس از بررسی مدیر ساختمان به حساب شما اعمال می‌شود");EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات / شماره پیگیری");content.addView(a,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));content.addView(n,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(12));Button b=btn("ثبت پرداخت برای بررسی",green);content.addView(b,new LinearLayout.LayoutParams(-1,dp(55)));b.setOnClickListener(v->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);callObj(new JSONObject().put("action","add_payment").put("amount_rial",rial).put("note",n.getText().toString()),z->{toast("پرداخت ثبت شد و در انتظار تأیید مدیر است");residentHome();});});}
    void adminHome(){frame("مدیرکل سامانه",false);adminDrawer();hero("مرکز کنترل سامانه 🔐","ساختمان‌ها، اشتراک‌ها و تنظیمات را مدیریت کنید.",Color.rgb(92,70,164));call("admin_dashboard",j->{JSONObject s=j.optJSONObject("summary");statRow("ساختمان‌ها",s==null?"0":s.optString("total_buildings"),"فعال",s==null?"0":s.optString("active"));statRow("آزمایشی",s==null?"0":s.optString("trial"),"در انتظار",s==null?"0":s.optString("pending"));section("مدیریت سریع","ابزارهای اصلی مدیر سامانه");action("مدیریت ساختمان‌ها","مشاهده و کنترل ساختمان‌ها","▣","admin_buildings",teal);action("مدیریت اشتراک‌ها","طرح‌ها و درخواست‌ها","★","admin_plans",blue);action("تنظیمات سامانه","نام برنامه، آزمایشی و درگاه","⚙","admin_settings",navy);});}
    void adminBuildings(){frame("مدیریت ساختمان‌ها",true);adminDrawer();section("ساختمان‌های ثبت‌شده","وضعیت اشتراک ساختمان‌ها");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("buildings");if(a==null||a.length()==0){empty("ساختمانی وجود ندارد");return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)item(x.optString("name","بدون نام"),"وضعیت: "+x.optString("subscription_status"));}});}
    void adminPlans(){frame("مدیریت اشتراک‌ها",true);adminDrawer();section("طرح‌های اشتراک","طرح‌ها و درخواست‌های ثبت‌شده");call("admin_dashboard",j->{JSONArray a=j.optJSONArray("plans");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);item(x.optString("name","طرح"),money(x.optDouble("price_rial"))+"  •  "+x.optInt("duration_days")+" روز");}JSONArray r=j.optJSONArray("requests");if(r!=null&&r.length()>0){section("درخواست‌ها","درخواست‌های ثبت‌شده");for(int i=0;i<r.length();i++){JSONObject x=r.optJSONObject(i);item("درخواست "+x.optString("id"),"وضعیت: "+statusFa(x.optString("status")));}}});}
    void adminSettings(){frame("تنظیمات سامانه",true);adminDrawer();section("تنظیمات فعلی","پارامترهای اصلی سامانه");call("admin_dashboard",j->{JSONObject x=j.optJSONObject("settings");if(x!=null){item("نام برنامه",x.optString("app_name"));item("دوره آزمایشی",x.optString("free_trial_days")+" روز");item("تأیید ایمیل",x.optBoolean("email_verification_enabled")?"فعال":"غیرفعال");item("درگاه پرداخت",x.optBoolean("payment_gateway_enabled")?"فعال":"غیرفعال");}});}
    void call(String action,OnJson cb){callObj(new JSONObject().put("action",action),cb);}
    void callObj(JSONObject b,OnJson cb){final int t=screenToken;io.submit(()->{try{JSONObject j=new JSONObject(post(b,session));if(j.has("error"))throw new Exception(j.getString("error"));runOnUiThread(()->{if(t==screenToken&&cb!=null)cb.ok(j);});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()==null?"خطای سامانه":e.getMessage()));}});}
    interface OnJson{void ok(JSONObject j);}
    String post(JSONObject body,String bearer)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(API).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(bearer!=null&&!bearer.isEmpty())c.setRequestProperty("Authorization","Bearer "+bearer);c.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String line;while((line=br.readLine())!=null)s.append(line);if(code>=400)throw new Exception("خطای سامانه ("+code+")");return s.toString();}
    long parseMoney(String s){try{return Long.parseLong(s.replace(",","").replace("٬","").trim());}catch(Exception e){return 0;}}
    String money(double rial){long toman=Math.round(rial/10.0);return String.format(Locale.US,"%,d تومان",toman);}
    String statusFa(String s){if("approved".equals(s))return "تأیید شده";if("rejected".equals(s))return "رد شده";if("pending".equals(s))return "در انتظار بررسی";return s==null?"-":s;}
    int statusColor(String s){if("approved".equals(s))return green;if("rejected".equals(s))return red;return gold;}
    void toast(String s){Toast.makeText(this,s==null?"خطا":s,Toast.LENGTH_LONG).show();}
}
