from pathlib import Path
import re

p=Path('app/src/main/java/com/sakhtemanyar/JalaliDate.java'); s=p.read_text()
old='private static int[] toGregorian(int jy,int jm,int jd){int jy2=jy-979;int days=365*jy2+(jy2/33)*8+((jy2%33+3)/4);for(int i=1;i<jm;i++)days+=i<=6?31:30;days+=jd-1;int gy=1600+400*(days/146097);days%=146097;boolean leap=true;if(days>=36525){days--;gy+=100*(days/36524);days%=36524;if(days>=365)days++;}gy+=4*(days/1461);days%=1461;if(days>=366){leap=false;days--;gy+=days/365;days%=365;}int[] md={31,28+(leap?1:0),31,30,31,30,31,31,30,31,30,31};int gm=1;while(gm<=12&&days>=md[gm-1]){days-=md[gm-1];gm++;}return new int[]{gy,gm,days+1};}'
new='private static int[] toGregorian(int jy,int jm,int jd){jy+=1595;int days=-355668+365*jy+(jy/33)*8+((jy%33+3)/4)+jd+(jm<=7?31*(jm-1):30*(jm-7)+186);int gy=400*(days/146097);days%=146097;if(days>36524){days--;gy+=100*(days/36524);days%=36524;if(days>=365)days++;}gy+=4*(days/1461);days%=1461;if(days>365){gy+=(days-1)/365;days=(days-1)%365;}boolean leap=(gy%4==0&&gy%100!=0)||gy%400==0;int[] md={31,28+(leap?1:0),31,30,31,30,31,31,30,31,30,31};int gm=1;while(gm<=12&&days>=md[gm-1]){days-=md[gm-1];gm++;}return new int[]{gy,gm,days+1};}'
assert old in s; p.write_text(s.replace(old,new,1))

p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java'); s=p.read_text()
assert s.count('void restoreSession(){')==1
s=s.replace('void restoreSession(){','void saveSession(String a,String r,String role){if(securePrefs!=null)securePrefs.edit().putString("session",a).putString("refresh_token",r==null?"":r).putString("role",role==null?"":role).apply();}\n\n    void restoreSession(){',1)
s=s.replace('session=j.getString("session");role=r;history.clear();','session=j.getString("session");role=r;saveSession(session,j.optString("refresh_token",""),role);history.clear();',1)
s=s.replace('void logout(){session="";role="";history.clear();showLogin();}','void logout(){session="";role="";if(securePrefs!=null)securePrefs.edit().clear().apply();history.clear();showLogin();}',1)
reg=re.compile(r'void register\(\)\{.*?\}\s*void managerHome\(\)',re.S)
newreg='''void register(){frame("ثبت ساختمان",true);section("شروع کار با ساختمان‌یار","ساختمان و حساب مدیر را یکجا بسازید");EditText n=input("نام ساختمان"),a=input("آدرس ساختمان"),u=input("نام کاربری مدیر"),p=input("رمز عبور حداقل ۸ کاراکتر"),cp=input("تکرار رمز عبور");p.setInputType(129);cp.setInputType(129);for(EditText e:new EditText[]{n,a,u,p,cp}){content.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(9));}Button b=btn("ثبت ساختمان و ورود",teal);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(v->io.submit(()->{try{String pw=p.getText().toString(),cw=cp.getText().toString();if(pw.length()<8||!pw.equals(cw)){runOnUiThread(()->toast("رمز عبور باید حداقل ۸ کاراکتر باشد و با تکرار رمز یکسان باشد"));return;}JSONObject j=new JSONObject().put("action","register_manager").put("building_name",n.getText().toString()).put("address",a.getText().toString()).put("username",u.getText().toString()).put("password",pw);JSONObject z=new JSONObject(post(j,null));if(z.has("error"))throw new Exception(z.getString("error"));session=z.getString("session");role="manager";saveSession(session,z.optString("refresh_token",""),role);history.clear();history.addLast("manager");runOnUiThread(this::managerHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}));} void managerHome()'''
m=reg.search(s); assert m, 'register method pattern not found'; s=s[:m.start()]+newreg+s[m.end():]
cb=re.compile(r'void cashbox\(\)\{.*?\}\s*void units\(\)',re.S)
newcb='''void cashbox(){frame("صندوق ساختمان",true);managerDrawer();hero("صندوق ساختمان","موجودی و گردش مالی ساختمان از محاسبه مرکزی امور مالی",gold);callFinance("manager_finance_dashboard",new JSONObject(),j->{JSONObject f=j.optJSONObject("fund");double income=f==null?0:f.optDouble("income"),expense=f==null?0:f.optDouble("expense"),balance=f==null?0:f.optDouble("balance"),pending=f==null?0:f.optDouble("pending_payments");statRow("موجودی محاسباتی",financeMoney(balance),"دریافت تأییدشده",financeMoney(income));statRow("هزینه ثبت‌شده",financeMoney(expense),"پرداخت در انتظار",financeMoney(pending));section("جزئیات گردش مالی","مبالغ از محاسبه مرکزی امور مالی خوانده می‌شوند");JSONArray e=j.optJSONArray("entries");if(e!=null&&e.length()>0){for(int i=0;i<e.length();i++){JSONObject x=e.optJSONObject(i);if(x!=null)item(x.optString("title","سند مالی"),("income".equalsIgnoreCase(x.optString("entry_type"))?"دریافت: ":"هزینه: ")+financeMoney(x.optDouble("amount_rial"))+"  •  "+financeDate(x.optString("entry_date",x.optString("created_at"))));}}else empty("سند مالی مستقیمی ثبت نشده است");});} void units()'''
m=cb.search(s); assert m, 'cashbox method pattern not found'; s=s[:m.start()]+newcb+s[m.end():]
p.write_text(s)

p=Path('app/src/main/java/com/sakhtemanyar/AdminActivity.java'); s=p.read_text(); ed=re.compile(r'void editBuilding\(JSONObject x\)\{.*?\}\s*void plans\(\)',re.S)
newed='''void editBuilding(JSONObject x){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=in("نام ساختمان");n.setText(x.optString("name"));EditText ad=in("آدرس");ad.setText(x.optString("address"));Spinner bs=new Spinner(this);String[] bsv={"active","stopped","archived"};bs.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,bsv));Spinner ss=new Spinner(this);String[] ssv={"trial","active","expired","suspended"};ss.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ssv));bs.setSelection(Math.max(0,java.util.Arrays.asList(bsv).indexOf(x.optString("building_status","active"))));ss.setSelection(Math.max(0,java.util.Arrays.asList(ssv).indexOf(x.optString("subscription_status","trial"))));l.addView(n);l.addView(gap(8));l.addView(ad);l.addView(gap(8));l.addView(bs);l.addView(gap(8));l.addView(ss);showDialog(new AlertDialog.Builder(this).setTitle("ویرایش ساختمان").setView(scrollWrap(l)).setPositiveButton("ذخیره",(d,w)->io.submit(()->{try{JSONObject q=new JSONObject().put("action","admin_building_update").put("building_id",x.optString("id")).put("name",n.getText().toString().trim()).put("address",ad.getText().toString().trim()).put("building_status",bsv[bs.getSelectedItemPosition()]).put("subscription_status",ssv[ss.getSelectedItemPosition()]);post(q,session);runOnUiThread(this::buildings);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}})).setNegativeButton("لغو",null).create());} void plans()'''
m=ed.search(s); assert m, 'editBuilding method pattern not found'; s=s[:m.start()]+newed+s[m.end():]; p.write_text(s)

p=Path('app/page.tsx'); s=p.read_text(); wd=re.compile(r'function jalali\(value: string\) \{.*?\n\}',re.S)
newwd='''function jalali(value: string) {\n  if (!value) return '-'\n  const m = value.match(/(\\d{4})-(\\d{2})-(\\d{2})/)\n  if (!m) return value\n  const gy=Number(m[1]),gm=Number(m[2]),gd=Number(m[3]); const gdm=[0,31,59,90,120,151,181,212,243,273,304,334]\n  let days=365*(gy-1600)+Math.floor((gy-1603)/4)-Math.floor((gy-1599)/100)+Math.floor((gy-1599)/400)+gd+gdm[gm-1]\n  if(gm>2&&((gy%4===0&&gy%100!==0)||gy%400===0))days++\n  let jDays=days-79; let jy=979+33*Math.floor(jDays/12053); let d=jDays%12053; jy+=4*Math.floor(d/1461); d%=1461\n  if(d>365){jy+=Math.floor((d-1)/365);d=(d-1)%365}\n  const jm=d<186?1+Math.floor(d/31):7+Math.floor((d-186)/30),jday=1+(d<186?d%31:(d-186)%30)\n  return `${jy}/${String(jm).padStart(2,'0')}/${String(jday).padStart(2,'0')}`\n}'''
m=wd.search(s); assert m; s=s[:m.start()]+newwd+s[m.end():]; p.write_text(s)
print('fix12 source transformations complete')
