from pathlib import Path
import re

p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java')
s=p.read_text()

def replace_method(name,new):
    global s
    start=s.index('    void '+name+'(')
    i=s.index('{',start); depth=0; end=None
    for k in range(i,len(s)):
        if s[k]=='{': depth+=1
        elif s[k]=='}':
            depth-=1
            if depth==0:
                end=k+1; break
    s=s[:start]+new+s[end:]

replace_method('frame', '''    void frame(String title,boolean inner){screenToken++; FrameLayout fr=new FrameLayout(this); fr.setBackgroundColor(bg); fr.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); setContentView(fr); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(bg); LinearLayout bar=new LinearLayout(this); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setPadding(dp(9),dp(7),dp(9),dp(7)); bar.setBackground(grad(navy,navy2,0)); TextView nav=tv(inner?"‹":"☰",31,white); nav.setGravity(Gravity.CENTER); bar.addView(nav,new LinearLayout.LayoutParams(dp(52),dp(50))); TextView t=tv(title,18,white); t.setTypeface(Typeface.DEFAULT,Typeface.BOLD); bar.addView(t,new LinearLayout.LayoutParams(0,dp(50),1)); TextView brand=tv("ساختمان‌یار",12,Color.rgb(190,224,220)); brand.setGravity(Gravity.CENTER); bar.addView(brand,new LinearLayout.LayoutParams(dp(92),dp(50))); root.addView(bar,new LinearLayout.LayoutParams(-1,dp(66))); ScrollView sv=new ScrollView(this); sv.setFillViewport(true); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(16),dp(16),dp(16),dp(32)); content.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); sv.addView(content); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1)); fr.addView(root,new FrameLayout.LayoutParams(-1,-1)); drawer=new LinearLayout(this); drawer.setOrientation(LinearLayout.VERTICAL); drawer.setPadding(dp(14),dp(16),dp(14),dp(22)); drawer.setBackgroundColor(white); drawer.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); FrameLayout.LayoutParams dl=new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.90),-1,Gravity.RIGHT); fr.addView(drawer,dl); drawer.setVisibility(View.GONE); nav.setOnClickListener(v->{if(inner)backPage();else toggleDrawer();}); }''')

replace_method('residentDialog', '''    void residentDialog(String unitId,String unitNo){final EditText n=input("نام و نام خانوادگی"),phone=input("شماره تلفن ساکن"),u=input("نام کاربری ساکن"),p=input("رمز عبور حداقل ۶ کاراکتر");p.setInputType(129);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{n,phone,u,p}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("حساب ساکن • واحد "+unitNo).setView(l).setNegativeButton("لغو",null).setPositiveButton("ساخت حساب",(d,w)->callObj(new JSONObject().put("action","create_resident").put("unit_id",unitId).put("username",u.getText().toString()).put("password",p.getText().toString()).put("full_name",n.getText().toString()).put("phone",phone.getText().toString()),z->toast("حساب ساکن ساخته شد"))).show(); }''')

replace_method('chargeDialog', '''    void chargeDialog(){final EditText t=input("عنوان هزینه / شارژ"),a=input("مبلغ کل به تومان"),d=input("توضیحات");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("ثبت شارژ / هزینه").setView(l).setNegativeButton("لغو",null).setPositiveButton("ادامه",(x,w)->chooseChargeAllocation(t.getText().toString(),a.getText().toString(),d.getText().toString())).show(); }\n    void chooseChargeAllocation(String title,String amount,String desc){call("dashboard",j->{JSONArray us=j.optJSONArray("units");if(us==null||us.length()==0){toast("ابتدا واحدها را ثبت کنید");return;}String[] labels=new String[us.length()];for(int i=0;i<us.length();i++){JSONObject u=us.optJSONObject(i);labels[i]="واحد "+u.optString("unit_no")+" • "+u.optInt("resident_count",0)+" نفر";}new AlertDialog.Builder(this).setTitle("نحوه تعلق هزینه").setSingleChoiceItems(new String[]{"مساوی بین واحدها","بر اساس تعداد نفرات"},0,(d,w)->{}).setMultiChoiceItems(labels,null,(d,w,checked)->{}).setNegativeButton("لغو",null).setPositiveButton("ثبت برای واحدهای انتخاب‌شده",(d,w)->{AlertDialog q=(AlertDialog)d;int mode=q.getListView().getCheckedItemPosition();ArrayList<String> ids=new ArrayList<>();for(int i=0;i<us.length();i++)if(q.getListView().isItemChecked(i))ids.add(us.optJSONObject(i).optString("id"));if(ids.isEmpty()){toast("حداقل یک واحد را انتخاب کنید");return;}long rial=Math.max(0,parseMoney(amount)*10);callObj(new JSONObject().put("action","add_charge").put("title",title).put("amount_rial",rial).put("description",desc).put("allocation_method",mode==1?"per_person":"per_unit").put("unit_ids",new JSONArray(ids)),z->{toast("هزینه ثبت شد و فقط برای واحدهای انتخاب‌شده تعلق گرفت");charges();});}).show();});}''')

replace_method('repairDialog', '''    void repairDialog(){final EditText t=input("عنوان تعمیر"),a=input("هزینه کل به تومان"),d=input("توضیحات");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("ثبت تعمیر").setView(l).setNegativeButton("لغو",null).setPositiveButton("انتخاب واحدها",(x,w)->chooseRepairUnits(t.getText().toString(),a.getText().toString(),d.getText().toString())).show(); }\n    void chooseRepairUnits(String title,String amount,String desc){call("dashboard",j->{JSONArray us=j.optJSONArray("units");if(us==null||us.length()==0){toast("ابتدا واحدها را ثبت کنید");return;}String[] labels=new String[us.length()];for(int i=0;i<us.length();i++)labels[i]="واحد "+us.optJSONObject(i).optString("unit_no");new AlertDialog.Builder(this).setTitle("تعمیر برای کدام واحدها؟").setMultiChoiceItems(labels,null,(d,w,c)->{}).setNegativeButton("لغو",null).setPositiveButton("ثبت تعمیر",(d,w)->{AlertDialog q=(AlertDialog)d;ArrayList<String> ids=new ArrayList<>();for(int i=0;i<us.length();i++)if(q.getListView().isItemChecked(i))ids.add(us.optJSONObject(i).optString("id"));if(ids.isEmpty()){toast("حداقل یک واحد را انتخاب کنید");return;}long rial=Math.max(0,parseMoney(amount)*10);callObj(new JSONObject().put("action","add_repair").put("title",title).put("amount_rial",rial).put("description",desc).put("unit_ids",new JSONArray(ids)),z->{toast("تعمیر ثبت شد");repairs();});}).show();});}''')

replace_method('repairs', '''    void repairs(){frame("تعمیرات",true);managerDrawer();section("تعمیرات","هر مورد را لمس کنید تا جزئیات، واحدها، فیش و عملیات مدیریتی باز شود");Button add=btn("＋ ثبت تعمیر جدید",red);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(12));add.setOnClickListener(v->repairDialog());call("dashboard",j->{JSONArray a=j.optJSONArray("repairs");if(a==null||a.length()==0){empty("هنوز تعمیراتی ثبت نشده است");return;}section("سوابق تعمیرات",null);for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)repairCard(x);}});}\n    void repairCard(JSONObject x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(box(white,19));TextView h=tv(x.optString("title","تعمیرات"),17,navy);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(h);c.addView(tv(money(x.optDouble("amount"))+"  •  "+JalaliDate.format(x.optString("created_at")),13,muted));c.addView(tv("برای واحدهای مشخص‌شده • وضعیت: "+statusFa(x.optString("status")),12,statusColor(x.optString("status"))));Button b=btn("مشاهده جزئیات  ›",blue);c.addView(b,new LinearLayout.LayoutParams(-1,dp(47)));b.setOnClickListener(v->repairDetails(x));content.addView(c,new LinearLayout.LayoutParams(-1,dp(142)));content.addView(gap(10));}\n    void repairDetails(JSONObject x){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(8),dp(4),dp(8),dp(4));l.addView(tv("مبلغ: "+money(x.optDouble("amount")),15,navy));l.addView(tv("توضیحات: "+x.optString("description","-"),14,muted));l.addView(tv("واحدها: از اطلاعات تخصیص ثبت‌شده",14,muted));if(!x.optString("receipt_url","").isEmpty())l.addView(tv("فیش / عکس تعمیر ثبت شده است",13,green));new AlertDialog.Builder(this).setTitle(x.optString("title","تعمیرات")).setView(l).setNegativeButton("بستن",null).setNeutralButton("حذف / ابطال",(d,w)->callObj(new JSONObject().put("action","delete_repair").put("repair_id",x.optString("id")),z->{toast("تعمیر حذف شد");repairs();})).setPositiveButton("ویرایش",(d,w)->editRepair(x)).show();}\n    void editRepair(JSONObject x){final EditText t=input("عنوان"),a=input("مبلغ تومان"),d=input("توضیحات");t.setText(x.optString("title",""));a.setText(String.valueOf(Math.round(x.optDouble("amount")/10.0)));d.setText(x.optString("description",""));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}new AlertDialog.Builder(this).setTitle("ویرایش تعمیر").setView(l).setNegativeButton("لغو",null).setPositiveButton("ذخیره",(q,w)->callObj(new JSONObject().put("action","update_repair").put("repair_id",x.optString("id")).put("title",t.getText().toString()).put("amount_rial",parseMoney(a.getText().toString())*10).put("description",d.getText().toString()),z->{toast("تعمیر ویرایش شد");repairs();})).show();}''')

# Make action cards roomier globally
s=s.replace('new LinearLayout.LayoutParams(dp(55),dp(58))','new LinearLayout.LayoutParams(dp(62),dp(64))')
s=s.replace('new LinearLayout.LayoutParams(0,dp(58),1)','new LinearLayout.LayoutParams(0,dp(64),1)')
s=s.replace('new LinearLayout.LayoutParams(dp(31),dp(58))','new LinearLayout.LayoutParams(dp(38),dp(64))')
s=s.replace('new LinearLayout.LayoutParams(-1,dp(70))','new LinearLayout.LayoutParams(-1,dp(82))')
s=s.replace('content.addView(gap(8));','content.addView(gap(11));')
p.write_text(s)
print('patched v2 ui')
