from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java'); s=p.read_text(encoding='utf-8')
if '    void repairDialog(' not in s:
    marker='    void repairs(){'
    method='''    void repairDialog(){call("dashboard",j->{final JSONArray us=j.optJSONArray("units");if(us==null||us.length()==0){toast("ابتدا واحدها را ثبت کنید");return;}final String[] labels=new String[us.length()];for(int i=0;i<us.length();i++)labels[i]="واحد "+us.optJSONObject(i).optString("unit_no");final EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات");receiptData="";receiptButton=btn("＋ آپلود عکس / فیش تعمیرات",red);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(v->{uploadTarget=3;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت تعمیرات").setMultiChoiceItems(labels,null,(q,w,c)->{}).setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت تعمیر",(q,w)->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);ListView list=((AlertDialog)q).getListView();JSONArray selected=new JSONArray();for(int i=0;i<us.length();i++)if(list!=null&&list.isItemChecked(i))selected.put(us.optJSONObject(i).optString("id"));if(selected.length()==0){toast("حداقل یک واحد را انتخاب کنید");return;}callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString().trim()).put("amount_rial",rial).put("description",d.getText().toString().trim()).put("unit_ids",selected).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("تعمیر ثبت شد");repairs();});}).show();});}\n'''
    s=s.replace(marker,method+marker,1); p.write_text(s,encoding='utf-8')
# Reuse the tested v3 replacements after ensuring repairDialog exists.
exec(Path('tools/patch_v3_ui.py').read_text(encoding='utf-8'),globals())
print('v4 applied')
