from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java'); s=p.read_text(encoding='utf-8')
def repl(name,new):
 global s
 st=s.index('    void '+name+'('); i=s.index('{',st); d=0
 for k in range(i,len(s)):
  if s[k]=='{': d+=1
  elif s[k]=='}':
   d-=1
   if d==0: s=s[:st]+new+s[k+1:]; return
repl('chargeDialog','''    void chargeDialog(){call("dashboard",j->{final JSONArray us=j.optJSONArray("units");if(us==null||us.length()==0){toast("ابتدا واحدها را ثبت کنید");return;}final String[] labels=new String[us.length()+1];final String[] ids=new String[us.length()+1];labels[0]="همه واحدها";ids[0]="";for(int i=0;i<us.length();i++){labels[i+1]="واحد "+us.optJSONObject(i).optString("unit_no")+" • "+us.optJSONObject(i).optInt("resident_count",0)+" نفر";ids[i+1]=us.optJSONObject(i).optString("id");}final EditText t=input("عنوان هزینه"),a=input("مبلغ کل به تومان"),d=input("توضیحات");final Spinner sel=new Spinner(this);sel.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));final String[] methods={"تقسیم مساوی بین واحدها","تقسیم بر اساس تعداد نفرات","فقط واحد انتخاب‌شده"};final Spinner method=new Spinner(this);method.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,methods));receiptData="";receiptButton=btn("＋ آپلود عکس / فیش هزینه",gold);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);l.addView(tv("واحدهای مشمول",12,muted),new LinearLayout.LayoutParams(-1,dp(30)));l.addView(sel,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(gap(7));l.addView(tv("روش محاسبه",12,muted),new LinearLayout.LayoutParams(-1,dp(30)));l.addView(method,new LinearLayout.LayoutParams(-1,dp(52)));l.addView(gap(7));for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(v->{uploadTarget=1;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت شارژ / هزینه").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(q,w)->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);int pos=sel.getSelectedItemPosition();String alloc=method.getSelectedItemPosition()==1?"per_person":method.getSelectedItemPosition()==2?"unit_specific":"per_unit";JSONArray selected=new JSONArray();if(pos==0){for(int i=0;i<us.length();i++)selected.put(us.optJSONObject(i).optString("id"));}else selected.put(ids[pos]);callObj(new JSONObject().put("action","add_charge").put("title",t.getText().toString().trim()).put("amount_rial",rial).put("description",d.getText().toString().trim()).put("allocation_method",alloc).put("unit_ids",selected).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("هزینه ثبت شد و فقط برای واحدهای مشخص‌شده اعمال شد");charges();});}).show();});}''')
repl('repairDialog','''    void repairDialog(){call("dashboard",j->{final JSONArray us=j.optJSONArray("units");if(us==null||us.length()==0){toast("ابتدا واحدها را ثبت کنید");return;}final String[] labels=new String[us.length()];for(int i=0;i<us.length();i++)labels[i]="واحد "+us.optJSONObject(i).optString("unit_no");final EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات");receiptData="";receiptButton=btn("＋ آپلود عکس / فیش تعمیرات",red);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);for(EditText e:new EditText[]{t,a,d}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(tv("واحدهای مشمول تعمیر",12,muted),new LinearLayout.LayoutParams(-1,dp(30)));l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(v->{uploadTarget=3;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت تعمیرات").setMultiChoiceItems(labels,null,(q,w,c)->{}).setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت تعمیر",(q,w)->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);ListView list=((AlertDialog)q).getListView();JSONArray selected=new JSONArray();for(int i=0;i<us.length();i++)if(list!=null&&list.isItemChecked(i))selected.put(us.optJSONObject(i).optString("id"));if(selected.length()==0){toast("حداقل یک واحد را انتخاب کنید");return;}callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString().trim()).put("amount_rial",rial).put("description",d.getText().toString().trim()).put("unit_ids",selected).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("تعمیر ثبت شد");repairs();});}).show();});}''')
repl('residentPay','''    void residentPay(){frame("ثبت پرداخت",true);residentDrawer();section("پرداخت‌های قابل پرداخت","روی هر مورد بزنید تا همان مبلغ برای واحد شما ثبت شود");call("dashboard",j->{JSONArray c=j.optJSONArray("charges");if(c!=null)for(int i=0;i<c.length();i++){JSONObject x=c.optJSONObject(i);if(x!=null){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(box(white,18));card.addView(tv(x.optString("title","شارژ"),16,navy));card.addView(tv(money(x.optDouble("amount_rial")),14,muted));Button pay=btn("پرداخت این مورد",green);card.addView(pay,new LinearLayout.LayoutParams(-1,dp(46)));String cid=x.optString("id");pay.setOnClickListener(v->residentPaymentFor(cid,null,x.optDouble("amount_rial")));content.addView(card,new LinearLayout.LayoutParams(-1,dp(112)));content.addView(gap(10));}}if(c==null||c.length()==0)empty("هزینه‌ای برای پرداخت ثبت نشده است");section("پرداخت آزاد","اگر پرداخت آزاد دارید مبلغ را وارد کنید");final EditText a=input("مبلغ به تومان"),n=input("شماره پیگیری / توضیحات");content.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(7));content.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(9));Button b=btn("ثبت پرداخت آزاد",green);content.addView(b,new LinearLayout.LayoutParams(-1,dp(54)));b.setOnClickListener(v->residentPaymentFor(null,null,parseMoney(a.getText().toString())*10));});}
    void residentPaymentFor(String chargeId,String repairId,double rial){if(rial<=0){toast("مبلغ نامعتبر است");return;}final EditText n=input("شماره پیگیری / توضیحات");receiptData="";receiptButton=btn("＋ آپلود عکس / فیش",green);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(v->{uploadTarget=2;pickImage();});new AlertDialog.Builder(this).setTitle("تأیید پرداخت").setMessage("مبلغ: "+money(rial)).setView(l).setNegativeButton("لغو",null).setPositiveButton("ارسال برای تأیید",(d,w)->callObj(new JSONObject().put("action","add_payment").put("amount_rial",Math.round(rial)).put("charge_id",chargeId==null?JSONObject.NULL:chargeId).put("repair_id",repairId==null?JSONObject.NULL:repairId).put("note",n.getText().toString().trim()).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("پرداخت و فیش برای مدیر ارسال شد");residentHome();})).show();}
''')
p.write_text(s,encoding='utf-8'); print('v3 applied')
