from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java')
s=p.read_text(encoding='utf-8')
start=s.index('    void residentItemCard(')
end=s.index('    void residentItemDetail(',start)
fixed='''    void residentItemCard(JSONObject x,boolean charge){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(box(white,19));double share=x.optJSONObject("my_allocation")!=null?x.optJSONObject("my_allocation").optDouble("allocated_amount_rial"):0;JSONArray pp=x.optJSONArray("related_payments");double paid=0;JSONObject pending=null;if(pp!=null)for(int i=0;i<pp.length();i++){JSONObject p=pp.optJSONObject(i);if(p!=null&&!"rejected".equals(p.optString("status"))){paid+=p.optDouble("amount");if("pending".equals(p.optString("status")))pending=p;}}final JSONObject pendingPay=pending;final double remaining=Math.max(0,share-paid);c.addView(tv(x.optString("title",charge?"شارژ / هزینه":"تعمیرات"),17,navy));c.addView(tv("سهم شما: "+financeMoney(share)+" • تاریخ: "+financeDate(x.optString(charge?"charge_date":"repair_date",x.optString("created_at"))),12,muted));c.addView(tv(remaining<=0?"🟢 تسویه شده":pendingPay!=null?"🟡 پرداخت در انتظار تأیید":"🔴 پرداخت نشده",13,statusColor(remaining<=0?"approved":pendingPay!=null?"pending":"rejected")));LinearLayout row=new LinearLayout(this);Button detail=btn("جزئیات",blue),pay=btn(remaining<=0?"تسویه شد":pendingPay!=null?"در انتظار تأیید":"💳 پرداخت این مورد",green),doc=btn("فیش مدیر",gold);row.addView(detail,new LinearLayout.LayoutParams(0,dp(46),1));row.addView(pay,new LinearLayout.LayoutParams(0,dp(46),1));row.addView(doc,new LinearLayout.LayoutParams(0,dp(46),1));c.addView(row);detail.setOnClickListener(v->residentItemDetail(x,charge));pay.setOnClickListener(v->{if(remaining>0&&pendingPay==null)residentPayItem(x,charge);});doc.setOnClickListener(v->showReceipt(x.optString("receipt_url","")));if(pendingPay!=null){Button ed=btn("✏ ویرایش پرداخت / فیش",blue);c.addView(ed,new LinearLayout.LayoutParams(-1,dp(46)));ed.setOnClickListener(v->residentEditPayment(pendingPay));}content.addView(c,new LinearLayout.LayoutParams(-1,-2));content.addView(gap(10));}
'''
s=s[:start]+fixed+s[end:]
p.write_text(s,encoding='utf-8')
print('finance lambda capture fixed')
