from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java')
s=p.read_text(encoding='utf-8')
if 'String rawPost(' not in s:
    raw=r'''String rawPost(JSONObject body,String auth)throws Exception{if(body==null)body=new JSONObject();String action=body.optString("action","");if(!body.has("request_id")&&java.util.Arrays.asList("add_charge","add_charge_finance","add_repair","add_repair_finance","manager_add_payment","approve_payment_finance","manager_finance_entry_create","request_subscription","register_manager").contains(action))body.put("request_id",java.util.UUID.randomUUID().toString());int tries=0;while(true){HttpURLConnection c=null;try{runOnUiThread(()->setBusy(true));URL u=new URL(API);c=(HttpURLConnection)u.openConnection();c.setRequestMethod("POST");c.setConnectTimeout(7000);c.setReadTimeout(9000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=UTF-8");if(auth!=null&&!auth.isEmpty())c.setRequestProperty("Authorization","Bearer "+auth);c.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();if(in==null)in=c.getInputStream();String out=new String(in.readAllBytes(),StandardCharsets.UTF_8);if(code==401&&auth!=null&&!"refresh_session".equals(action)&&securePrefs!=null){String rt=securePrefs.getString("refresh_token","");if(!rt.isEmpty()){JSONObject rb=new JSONObject().put("action","refresh_session").put("refresh_token",rt);String rr=rawPost(rb,null);JSONObject rj=new JSONObject(rr);String na=rj.optString("access_token",rj.optString("session",""));String nr=rj.optString("refresh_token",rt);if(!na.isEmpty()){session=na;securePrefs.edit().putString("session",na).putString("refresh_token",nr).apply();return rawPost(body,na);}}}if(code>=500&&tries<2){tries++;continue;}if(code>=400)throw new RuntimeException(new JSONObject(out).optString("error","خطای سرور"));return out;}catch(java.net.UnknownHostException|java.net.ConnectException e){if(tries<2){tries++;continue;}throw new RuntimeException("اینترنت در دسترس نیست");}catch(java.net.SocketTimeoutException e){if(tries<1){tries++;continue;}throw new RuntimeException("پاسخ سرور دیر دریافت شد. دوباره تلاش کنید.");}finally{if(c!=null)c.disconnect();runOnUiThread(()->setBusy(false));}}}'''
    pos=s.rfind('\n}')
    s=s[:pos]+'\n    '+raw+s[pos:]
p.write_text(s,encoding='utf-8')
print('V18 rawPost fix applied')
