from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java')
s=p.read_text(encoding='utf-8')

def replace_method(name,next_name,new):
    global s
    a=s.index('    void '+name+'(){')
    b=s.index('    void '+next_name+'(){',a)
    s=s[:a]+new+s[b:]

def add_helper_once(marker, code):
    global s
    if code.strip() not in s:
        s=s.replace(marker,marker+code,1)

if 'String jalaliIso(EditText e)' not in s:
    marker='    void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,901);}\n'
    helper='''    String jalaliIso(EditText e){String v=e.getText().toString().trim().replace('-', '/');if(v.isEmpty())return new java.text.SimpleDateFormat("yyyy-MM-dd",java.util.Locale.US).format(new java.util.Date());return JalaliDate.toGregorianIso(v);}\n    EditText jalaliDateInput(){EditText e=input("تاریخ شمسی (مثلاً ۱۴۰۵/۰۶/۲۱)");e.setText(JalaliDate.now());return e;}\n    JSONArray toJsonArray(ArrayList<String> xs){JSONArray a=new JSONArray();for(String x:xs)a.put(x);return a;}\n    ArrayList<String> selectedUnits(LinearLayout box,ArrayList<String> ids){ArrayList<String> out=new ArrayList<>();for(int i=0;i<box.getChildCount();i++){View v=box.getChildAt(i);if(v instanceof CheckBox && ((CheckBox)v).isChecked())out.add(ids.get(i));}return out;}\n    void unitSelector(LinearLayout host,JSONArray units,boolean allDefault){final RadioGroup mode=new RadioGroup(this);mode.setOrientation(RadioGroup.VERTICAL);mode.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);RadioButton all=new RadioButton(this);all.setId(View.generateViewId());all.setText("همه ساکنین");RadioButton some=new RadioButton(this);some.setId(View.generateViewId());some.setText("انتخاب واحدهای مورد نظر");mode.addView(all);mode.addView(some);host.addView(mode,new LinearLayout.LayoutParams(-1,dp(92)));final LinearLayout checks=new LinearLayout(this);checks.setOrientation(LinearLayout.VERTICAL);checks.setVisibility(allDefault?View.GONE:View.VISIBLE);final ArrayList<String> ids=new ArrayList<>();if(units!=null)for(int i=0;i<units.length();i++){JSONObject u=units.optJSONObject(i);if(u!=null){CheckBox c=new CheckBox(this);c.setText("واحد "+u.optString("unit_no","-"));c.setTextSize(14);c.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);checks.addView(c,new LinearLayout.LayoutParams(-1,dp(48)));ids.add(u.optString("id",""));}}host.addView(checks,new LinearLayout.LayoutParams(-1,dp(Math.max(48,ids.size()*48))));all.setChecked(allDefault);some.setChecked(!allDefault);mode.setOnCheckedChangeListener((g,id)->{checks.setVisibility(id==all.getId()?View.GONE:View.VISIBLE);});host.setTag(new Object[]{all,some,checks,ids});}\n    ArrayList<String> getSelectedUnitIds(LinearLayout host){Object[] x=(Object[])host.getTag();RadioButton all=(RadioButton)x[0];LinearLayout checks=(LinearLayout)x[2];@SuppressWarnings("unchecked") ArrayList<String> ids=(ArrayList<String>)x[3];ArrayList<String> out=new ArrayList<>();if(all.isChecked())out.addAll(ids);else out=selectedUnits(checks,ids);return out;}\n'''
    s=s.replace(marker,marker+helper,1)

replace_method('chargeDialog','repairs','''    void chargeDialog(){\n        call("dashboard",j->{JSONArray units=j.optJSONArray("units");final EditText t=input("عنوان شارژ / هزینه"),a=input("مبلغ به تومان"),d=input("توضیحات"),date=jalaliDateInput();final LinearLayout selector=new LinearLayout(this);selector.setOrientation(LinearLayout.VERTICAL);selector.setPadding(dp(4),0,dp(4),0);unitSelector(selector,units,true);receiptData="";receiptButton=btn("＋ آپلود عکس / فیش هزینه",gold);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);l.addView(tv("این هزینه برای چه کسانی است؟",12,muted));l.addView(selector,new LinearLayout.LayoutParams(-1,-2));for(EditText e:new EditText[]{t,a,d,date}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(v->{uploadTarget=1;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت شارژ یا هزینه").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(x,w)->{ArrayList<String> chosen=getSelectedUnitIds(selector);if(chosen.isEmpty()){toast("حداقل یک واحد را انتخاب کنید");return;}long rial=Math.max(0,parseMoney(a.getText().toString())*10);if(rial<=0){toast("مبلغ را وارد کنید");return;}JSONObject q=new JSONObject().put("action","add_charge").put("title",t.getText().toString().trim()).put("amount_rial",rial).put("description",d.getText().toString().trim()).put("unit_ids",toJsonArray(chosen)).put("allocation_method","per_unit").put("due_date",jalaliIso(date)).put("charge_date",jalaliIso(date)).put("receipt_url",receiptData);callObj(q,z->{receiptData="";receiptButton=null;toast("هزینه ثبت شد");charges();});}).show();});\n    }\n''')
replace_method('repairs','payments','''    void repairs(){\n        frame("تعمیرات",true);managerDrawer();section("تعمیرات ساختمان","تعمیر را به همه یا فقط واحدهای انتخابی اختصاص دهید");Button add=btn("＋ ثبت تعمیر جدید",red);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(12));add.setOnClickListener(v->{call("dashboard",j->{JSONArray units=j.optJSONArray("units");final EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات"),date=jalaliDateInput();final LinearLayout selector=new LinearLayout(this);selector.setOrientation(LinearLayout.VERTICAL);selector.setPadding(dp(4),0,dp(4),0);unitSelector(selector,units,true);receiptData="";receiptButton=btn("＋ آپلود عکس / فیش تعمیرات",red);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);l.addView(tv("این تعمیر برای چه کسانی است؟",12,muted));l.addView(selector,new LinearLayout.LayoutParams(-1,-2));for(EditText e:new EditText[]{t,a,d,date}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(q->{uploadTarget=3;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت تعمیرات").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(q,w)->{ArrayList<String> chosen=getSelectedUnitIds(selector);if(chosen.isEmpty()){toast("حداقل یک واحد را انتخاب کنید");return;}long rial=Math.max(0,parseMoney(a.getText().toString())*10);if(rial<=0){toast("مبلغ را وارد کنید");return;}callObj(new JSONObject().put("action","add_repair").put("title",t.getText().toString().trim()).put("amount_rial",rial).put("description",d.getText().toString().trim()).put("unit_ids",toJsonArray(chosen)).put("repair_date",jalaliIso(date)).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("تعمیر ثبت شد");repairs();});}).show();});});call("dashboard",j->{JSONArray r=j.optJSONArray("repairs");if(r==null||r.length()==0){empty("هنوز تعمیراتی ثبت نشده است");return;}for(int i=0;i<r.length();i++){JSONObject x=r.optJSONObject(i);if(x==null)continue;String title=x.optString("title","تعمیر"),amount=x.optString("amount_rial",x.optString("amount","0")),receipt=x.optString("receipt_url","");String ds=x.optString("repair_date","");item(title,"تاریخ: "+JalaliDate.format(ds)+"  •  مبلغ: "+formatToman(amount)+(receipt.isEmpty()?"":"  •  📎 پیوست"));}});\n    }\n''')
replace_method('payments','plans','''    void payments(){\n        frame("پرداخت‌ها",true);managerDrawer();section("ثبت و بررسی پرداخت‌ها","پرداخت ساکن را به واحد درست ثبت و بررسی کنید");Button add=btn("＋ ثبت پرداخت برای ساکن",green);content.addView(add,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(12));add.setOnClickListener(v->{call("dashboard",j->{JSONArray units=j.optJSONArray("units");ArrayList<String> labels=new ArrayList<>(),ids=new ArrayList<>();if(units!=null)for(int i=0;i<units.length();i++){JSONObject u=units.optJSONObject(i);if(u!=null){labels.add("واحد "+u.optString("unit_no","-"));ids.add(u.optString("id",""));}}final Spinner unit=new Spinner(this);unit.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,labels));final EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات / شماره پیگیری"),date=jalaliDateInput();receiptData="";receiptButton=btn("＋ آپلود عکس / فیش پرداخت",green);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(10),0,dp(10),0);l.addView(tv("انتخاب واحد ساکن",12,muted),new LinearLayout.LayoutParams(-1,dp(30)));l.addView(unit,new LinearLayout.LayoutParams(-1,dp(54)));for(EditText e:new EditText[]{a,n,date}){l.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(7));}l.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(50)));receiptButton.setOnClickListener(q->{uploadTarget=2;pickImage();});new AlertDialog.Builder(this).setTitle("ثبت پرداخت برای ساکن").setView(l).setNegativeButton("لغو",null).setPositiveButton("ثبت",(q,w)->{if(ids.isEmpty()){toast("هیچ واحدی وجود ندارد");return;}long rial=Math.max(0,parseMoney(a.getText().toString())*10);callObj(new JSONObject().put("action","add_payment").put("unit_id",ids.get(unit.getSelectedItemPosition())).put("amount_rial",rial).put("paid_at",jalaliIso(date)).put("note",n.getText().toString().trim()).put("receipt_url",receiptData),z->{receiptData="";receiptButton=null;toast("پرداخت ثبت شد");payments();});}).show();});});call("dashboard",j->{JSONArray p=j.optJSONArray("payments");if(p==null||p.length()==0){empty("هنوز پرداختی ثبت نشده است");return;}for(int i=0;i<p.length();i++){JSONObject x=p.optJSONObject(i);if(x==null)continue;String st=x.optString("status","pending"),label=st.equals("approved")?"تأیید شده":st.equals("rejected")?"رد شده":"در انتظار بررسی";item("پرداخت واحد "+x.optString("unit_id","-"),"تاریخ: "+JalaliDate.format(x.optString("paid_at",""))+"  •  مبلغ: "+formatToman(x.optString("amount","0"))+" • "+label);}});\n    }\n''')
replace_method('residentPay','adminHome','''    void residentPay(){\n        frame("ثبت پرداخت",true);residentDrawer();section("ثبت پرداخت جدید","مبلغ را برای مدیر ارسال کنید؛ واحد شما خودکار ثبت می‌شود");EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات / شماره پیگیری"),date=jalaliDateInput();content.addView(a,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(8));content.addView(n,new LinearLayout.LayoutParams(-1,dp(56)));content.addView(gap(8));content.addView(date,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(gap(10));receiptData="";receiptButton=btn("＋ آپلود عکس / فیش پرداخت",green);content.addView(receiptButton,new LinearLayout.LayoutParams(-1,dp(52)));content.addView(gap(12));Button b=btn("ثبت پرداخت برای بررسی مدیر",green);content.addView(b,new LinearLayout.LayoutParams(-1,dp(55)));receiptButton.setOnClickListener(v->{uploadTarget=2;pickImage();});b.setOnClickListener(v->{long rial=Math.max(0,parseMoney(a.getText().toString())*10);if(rial<=0){toast("مبلغ پرداخت را وارد کنید");return;}callObj(new JSONObject().put("action","add_payment").put("amount_rial",rial).put("paid_at",jalaliIso(date)).put("note",n.getText().toString().trim()).put("receipt_url",receiptData),z->{toast("پرداخت با موفقیت ثبت شد");receiptData="";receiptButton=null;residentHome();});});}\n''')
p.write_text(s,encoding='utf-8')
print('v5 patched')
