from pathlib import Path
p=Path('app/src/main/java/com/sakhtemanyar/MainActivity.java')
s=p.read_text(encoding='utf-8')
exec(Path('tools/patch_v3_ui.py').read_text(encoding='utf-8'),globals())
today='new java.text.SimpleDateFormat("yyyy-MM-dd", java.util.Locale.US).format(new java.util.Date())'
s=s.replace('final EditText t=input("عنوان هزینه"),a=input("مبلغ کل به تومان"),d=input("توضیحات");','final EditText t=input("عنوان هزینه"),a=input("مبلغ کل به تومان"),d=input("توضیحات"),date=input("تاریخ هزینه (YYYY-MM-DD)");date.setText('+today+');')
s=s.replace('for(EditText e:new EditText[]{t,a,d})','for(EditText e:new EditText[]{t,a,d,date})',1)
s=s.replace('.put("description",d.getText().toString().trim()).put("allocation_method",alloc)', '.put("description",d.getText().toString().trim()).put("due_date",date.getText().toString().trim()).put("allocation_method",alloc)',1)
s=s.replace('final EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات");','final EditText t=input("عنوان تعمیر"),a=input("مبلغ به تومان"),d=input("توضیحات"),date=input("تاریخ تعمیر (YYYY-MM-DD)");date.setText('+today+');')
s=s.replace('for(EditText e:new EditText[]{t,a,d})','for(EditText e:new EditText[]{t,a,d,date})',1)
s=s.replace('.put("description",d.getText().toString().trim()).put("unit_ids",selected)', '.put("description",d.getText().toString().trim()).put("repair_date",date.getText().toString().trim()).put("unit_ids",selected)',1)
s=s.replace('EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات / شماره پیگیری");', 'EditText a=input("مبلغ پرداخت به تومان"),n=input("توضیحات / شماره پیگیری"),date=input("تاریخ پرداخت (YYYY-MM-DD)");date.setText('+today+');')
s=s.replace('l.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));', 'l.addView(a,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(date,new LinearLayout.LayoutParams(-1,dp(54)));',1)
s=s.replace('.put("amount_rial",rial).put("note",n.getText().toString().trim()).put("receipt_url",receiptData)', '.put("amount_rial",rial).put("paid_at",date.getText().toString().trim()).put("note",n.getText().toString().trim()).put("receipt_url",receiptData)',1)
s=s.replace('final EditText n=input("شماره پیگیری / توضیحات");receiptData="";', 'final EditText n=input("شماره پیگیری / توضیحات"),date=input("تاریخ پرداخت (YYYY-MM-DD)");date.setText('+today+');receiptData="";',1)
s=s.replace('l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(receiptButton', 'l.addView(n,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(date,new LinearLayout.LayoutParams(-1,dp(54)));l.addView(gap(8));l.addView(receiptButton',1)
s=s.replace('.put("repair_id",repairId==null?JSONObject.NULL:repairId).put("note",n.getText().toString().trim())', '.put("repair_id",repairId==null?JSONObject.NULL:repairId).put("paid_at",date.getText().toString().trim()).put("note",n.getText().toString().trim())',1)
p.write_text(s,encoding='utf-8')
print('v4 dates applied')
